import type { SupportedLanguage } from "@/lib/i18n/types";

export type ActiveSessionMuscleLoadCopy = { title: string; description: string; savedOnly: string; updating: string; noSavedSets: string; partial: string; unavailable: string; loadFailed: string; retry: string };
const COPY: Record<SupportedLanguage, ActiveSessionMuscleLoadCopy> = {
  en: { title: "Muscle Load So Far", description: "Based only on completed sets saved to Plaivra. Warm-up sets are excluded.", savedOnly: "Saved sets only", updating: "Updating from saved sets…", noSavedSets: "Finish and save a working set to start the heat map.", partial: "Some exercises do not have a detailed mapping. Mapped muscles remain visible.", unavailable: "Muscle load is unavailable for the saved exercises in this session.", loadFailed: "Muscle load could not refresh. Your workout and saved sets are unaffected.", retry: "Retry" },
  de: { title: "Muskelbelastung bisher", description: "Nur aus abgeschlossenen und in Plaivra gespeicherten Sätzen. Aufwärmsätze zählen nicht.", savedOnly: "Nur gespeicherte Sätze", updating: "Gespeicherte Sätze werden aktualisiert…", noSavedSets: "Beende und speichere einen Arbeitssatz, um die Heatmap zu starten.", partial: "Für einige Übungen fehlt eine genaue Zuordnung. Zugeordnete Muskeln bleiben sichtbar.", unavailable: "Für die gespeicherten Übungen dieser Einheit ist keine Muskelbelastung verfügbar.", loadFailed: "Die Muskelbelastung konnte nicht aktualisiert werden. Training und Sätze bleiben gespeichert.", retry: "Erneut versuchen" },
  ar: { title: "حمل العضلات حتى الآن", description: "يعتمد فقط على المجموعات المكتملة والمحفوظة في Plaivra. مجموعات الإحماء لا تُحسب.", savedOnly: "المجموعات المحفوظة فقط", updating: "جارٍ التحديث من المجموعات المحفوظة…", noSavedSets: "أكمل واحفظ مجموعة عمل لبدء الخريطة الحرارية.", partial: "بعض التمارين ليس لها توزيع تفصيلي. ستظل العضلات المعروفة ظاهرة.", unavailable: "حمل العضلات غير متاح للتمارين المحفوظة في هذه الجلسة.", loadFailed: "تعذر تحديث حمل العضلات. التمرين والمجموعات المحفوظة لم تتأثر.", retry: "إعادة المحاولة" }
};
export function getActiveSessionMuscleLoadCopy(language: SupportedLanguage): ActiveSessionMuscleLoadCopy { return COPY[language] ?? COPY.en; }
