import type { SupportedLanguage } from "@/lib/i18n/types";
import type { MuscleHeatMapLabels } from "@/components/train/muscle-heat-map/details-panel";
import type { AdvancedMuscleTargetId } from "./advanced-atlas";

const copy = {
  "en": {
    "plannedTitle": "Planned Muscle Load",
    "plannedDescription": "Updates immediately from this unsaved plan draft. No data is written until you save.",
    "balanceTitle": "Plan Balance Review",
    "balanceDescription": "Review the full plan cycle before saving. Unmapped exercises are excluded and reported.",
    "weeklyTitle": "Weekly Muscle Load",
    "weeklyDescription": "Estimated from the saved plan's prescribed sets.",
    "exercisePreviewTitle": "Muscle preview",
    "exercisePreviewDescription": "Focus one exercise to review its approved regional mapping.",
    "previewAction": "Preview muscles",
    "currentDay": "Current day",
    "entirePlan": "Entire plan",
    "front": "Front",
    "back": "Back",
    "coverage": "Mapping coverage",
    "covered": "{included} of {total} exercises mapped",
    "partialDisclosure": "Some exercises do not have a reviewed advanced mapping yet. They were excluded rather than guessed.",
    "unavailableDisclosure": "No reviewed advanced mapping is available for this selection.",
    "emptyDisclosure": "Add exercises to see planned muscle load.",
    "close": "Close",
    "noSelection": "Select a highlighted region for details.",
    "loading": "Loading muscle analysis…",
    "empty": "No exercises to analyze.",
    "partial": "Partial muscle analysis",
    "unavailable": "Advanced muscle analysis unavailable",
    "error": "Muscle analysis could not be calculated.",
    "detailUnavailable": "Detailed regional mapping is unavailable for this broad-only item.",
    "broadIncluded": "Additional broad mapped contribution is included.",
    "none": "None",
    "light": "Light",
    "moderate": "Moderate",
    "high": "High",
    "primary": "Primary",
    "coPrimary": "Co-primary",
    "secondary": "Secondary",
    "stabilizer": "Stabilizer",
    "focusPrompt": "Choose Preview muscles on one exercise. The map is shown once here, not on every result card."
  },
  "de": {
    "plannedTitle": "Geplante Muskelbelastung",
    "plannedDescription": "Wird sofort aus dem ungespeicherten Planentwurf berechnet. Erst beim Speichern werden Daten geschrieben.",
    "balanceTitle": "Überprüfung der Planbalance",
    "balanceDescription": "Prüfe den gesamten Planzyklus vor dem Speichern. Nicht zugeordnete Übungen werden ausgeschlossen und gemeldet.",
    "weeklyTitle": "Wöchentliche Muskelbelastung",
    "weeklyDescription": "Geschätzt anhand der vorgegebenen Sätze im gespeicherten Plan.",
    "exercisePreviewTitle": "Muskelvorschau",
    "exercisePreviewDescription": "Fokussiere eine Übung, um ihre geprüfte regionale Zuordnung zu sehen.",
    "previewAction": "Muskeln anzeigen",
    "currentDay": "Aktueller Tag",
    "entirePlan": "Gesamter Plan",
    "front": "Vorne",
    "back": "Hinten",
    "coverage": "Zuordnungsabdeckung",
    "covered": "{included} von {total} Übungen zugeordnet",
    "partialDisclosure": "Einige Übungen haben noch keine geprüfte erweiterte Zuordnung. Sie wurden ausgeschlossen und nicht geschätzt.",
    "unavailableDisclosure": "Für diese Auswahl ist keine geprüfte erweiterte Zuordnung verfügbar.",
    "emptyDisclosure": "Füge Übungen hinzu, um die geplante Muskelbelastung zu sehen.",
    "close": "Schließen",
    "noSelection": "Wähle eine markierte Region für Details.",
    "loading": "Muskelanalyse wird geladen…",
    "empty": "Keine Übungen zur Analyse.",
    "partial": "Teilweise Muskelanalyse",
    "unavailable": "Erweiterte Muskelanalyse nicht verfügbar",
    "error": "Die Muskelanalyse konnte nicht berechnet werden.",
    "detailUnavailable": "Für dieses breite Ziel ist keine regionale Detailzuordnung verfügbar.",
    "broadIncluded": "Zusätzlicher breiter Zuordnungsbeitrag ist enthalten.",
    "none": "Keine",
    "light": "Leicht",
    "moderate": "Mittel",
    "high": "Hoch",
    "primary": "Primär",
    "coPrimary": "Co-primär",
    "secondary": "Sekundär",
    "stabilizer": "Stabilisator",
    "focusPrompt": "Wähle bei einer Übung „Muskeln anzeigen“. Die Karte erscheint einmal hier, nicht auf jeder Ergebniskarte."
  },
  "ar": {
    "plannedTitle": "الحمل العضلي المخطط",
    "plannedDescription": "يتحدث فورًا من مسودة الخطة غير المحفوظة. لا تتم كتابة أي بيانات قبل الحفظ.",
    "balanceTitle": "مراجعة توازن الخطة",
    "balanceDescription": "راجع دورة الخطة كاملة قبل الحفظ. التمارين غير المرتبطة تُستبعد ويُوضّح عددها.",
    "weeklyTitle": "الحمل العضلي الأسبوعي",
    "weeklyDescription": "تقدير مبني على المجموعات المحددة في الخطة المحفوظة.",
    "exercisePreviewTitle": "معاينة العضلات",
    "exercisePreviewDescription": "ركز على تمرين واحد لمراجعة ربطه الإقليمي المعتمد.",
    "previewAction": "معاينة العضلات",
    "currentDay": "اليوم الحالي",
    "entirePlan": "الخطة كاملة",
    "front": "الأمام",
    "back": "الخلف",
    "coverage": "تغطية الربط",
    "covered": "تم ربط {included} من {total} تمرين",
    "partialDisclosure": "بعض التمارين لا تملك ربطًا متقدمًا معتمدًا بعد. تم استبعادها بدل التخمين.",
    "unavailableDisclosure": "لا يوجد ربط عضلي متقدم معتمد لهذا الاختيار.",
    "emptyDisclosure": "أضف تمارين لعرض الحمل العضلي المخطط.",
    "close": "إغلاق",
    "noSelection": "اختر منطقة ملوّنة لعرض التفاصيل.",
    "loading": "جارٍ تحميل تحليل العضلات…",
    "empty": "لا توجد تمارين للتحليل.",
    "partial": "تحليل عضلي جزئي",
    "unavailable": "التحليل العضلي المتقدم غير متاح",
    "error": "تعذر حساب تحليل العضلات.",
    "detailUnavailable": "الربط الإقليمي التفصيلي غير متاح لهذا الهدف العام.",
    "broadIncluded": "تم تضمين مساهمة إضافية من الربط العام.",
    "none": "بدون",
    "light": "خفيف",
    "moderate": "متوسط",
    "high": "مرتفع",
    "primary": "أساسية",
    "coPrimary": "أساسية مشتركة",
    "secondary": "ثانوية",
    "stabilizer": "تثبيت",
    "focusPrompt": "اضغط «معاينة العضلات» على تمرين واحد. تظهر الخريطة مرة واحدة هنا، وليس داخل كل بطاقة نتيجة."
  }
} as const;

const targetNames: Record<SupportedLanguage, Record<AdvancedMuscleTargetId, string>> = {
  en: {
    "neck.sternocleidomastoid": "Sternocleidomastoid",
    "trapezius.upper": "Upper trapezius",
    "trapezius.middle": "Middle trapezius",
    "trapezius.lower": "Lower trapezius",
    "deltoid.anterior": "Anterior deltoid",
    "deltoid.lateral": "Lateral deltoid",
    "deltoid.posterior": "Posterior deltoid",
    "pectoralis.upper": "Upper chest",
    "pectoralis.middle": "Middle chest",
    "pectoralis.lower": "Lower chest",
    "pectoralis.outer": "Outer chest",
    "infraspinatus": "Infraspinatus",
    "teres_minor": "Teres minor",
    "teres_major": "Teres major",
    "latissimus.upper": "Upper lats",
    "latissimus.middle": "Middle lats",
    "latissimus.lower": "Lower lats",
    "latissimus.outer": "Outer lats",
    "serratus.anterior": "Serratus anterior",
    "biceps.long_head": "Biceps long head",
    "biceps.short_head": "Biceps short head",
    "brachialis": "Brachialis",
    "triceps.long_head": "Triceps long head",
    "triceps.lateral_head": "Triceps lateral head",
    "triceps.medial_head": "Triceps medial head",
    "brachioradialis": "Brachioradialis",
    "forearm.pronator_teres": "Pronator teres",
    "forearm.flexor_mass": "Forearm flexors",
    "forearm.extensor_mass": "Forearm extensors",
    "rectus_abdominis.upper": "Upper abs",
    "rectus_abdominis.middle": "Middle abs",
    "rectus_abdominis.lower": "Lower abs",
    "oblique.external_upper": "Upper external obliques",
    "oblique.external_lower": "Lower external obliques",
    "spinal_erectors.upper": "Upper spinal erectors",
    "spinal_erectors.lower": "Lower spinal erectors",
    "hip_flexors.anterior": "Anterior hip flexors",
    "tensor_fasciae_latae": "Tensor fasciae latae",
    "gluteus.medius": "Gluteus medius",
    "gluteus_maximus.upper": "Upper gluteus maximus",
    "gluteus_maximus.middle": "Middle gluteus maximus",
    "gluteus_maximus.lower": "Lower gluteus maximus",
    "quadriceps.rectus_femoris": "Rectus femoris",
    "quadriceps.vastus_lateralis": "Vastus lateralis",
    "quadriceps.vastus_medialis": "Vastus medialis",
    "adductors.anterior_region": "Anterior adductors",
    "adductors.posterior_region": "Posterior adductors",
    "hamstrings.biceps_femoris_long_head": "Biceps femoris long head",
    "hamstrings.biceps_femoris_short_head": "Biceps femoris short head",
    "hamstrings.semitendinosus": "Semitendinosus",
    "hamstrings.semimembranosus": "Semimembranosus",
    "lower_leg.tibialis_anterior": "Tibialis anterior",
    "lower_leg.fibularis": "Fibularis",
    "calf.gastrocnemius_medial": "Medial gastrocnemius",
    "calf.gastrocnemius_lateral": "Lateral gastrocnemius",
    "calf.soleus": "Soleus"
  },
  de: {
    "neck.sternocleidomastoid": "Kopfwender",
    "trapezius.upper": "Oberer Trapezmuskel",
    "trapezius.middle": "Mittlerer Trapezmuskel",
    "trapezius.lower": "Unterer Trapezmuskel",
    "deltoid.anterior": "Vorderer Deltamuskel",
    "deltoid.lateral": "Seitlicher Deltamuskel",
    "deltoid.posterior": "Hinterer Deltamuskel",
    "pectoralis.upper": "Obere Brust",
    "pectoralis.middle": "Mittlere Brust",
    "pectoralis.lower": "Untere Brust",
    "pectoralis.outer": "Äußere Brust",
    "infraspinatus": "Untergrätenmuskel",
    "teres_minor": "Kleiner Rundmuskel",
    "teres_major": "Großer Rundmuskel",
    "latissimus.upper": "Oberer Latissimus",
    "latissimus.middle": "Mittlerer Latissimus",
    "latissimus.lower": "Unterer Latissimus",
    "latissimus.outer": "Äußerer Latissimus",
    "serratus.anterior": "Vorderer Sägemuskel",
    "biceps.long_head": "Langer Bizepskopf",
    "biceps.short_head": "Kurzer Bizepskopf",
    "brachialis": "Armbeuger",
    "triceps.long_head": "Langer Trizepskopf",
    "triceps.lateral_head": "Seitlicher Trizepskopf",
    "triceps.medial_head": "Medialer Trizepskopf",
    "brachioradialis": "Oberarmspeichenmuskel",
    "forearm.pronator_teres": "Runder Einwärtsdreher",
    "forearm.flexor_mass": "Unterarmbeuger",
    "forearm.extensor_mass": "Unterarmstrecker",
    "rectus_abdominis.upper": "Oberer Bauch",
    "rectus_abdominis.middle": "Mittlerer Bauch",
    "rectus_abdominis.lower": "Unterer Bauch",
    "oblique.external_upper": "Obere äußere schräge Bauchmuskeln",
    "oblique.external_lower": "Untere äußere schräge Bauchmuskeln",
    "spinal_erectors.upper": "Obere Rückenstrecker",
    "spinal_erectors.lower": "Untere Rückenstrecker",
    "hip_flexors.anterior": "Vordere Hüftbeuger",
    "tensor_fasciae_latae": "Schenkelbindenspanner",
    "gluteus.medius": "Mittlerer Gesäßmuskel",
    "gluteus_maximus.upper": "Oberer großer Gesäßmuskel",
    "gluteus_maximus.middle": "Mittlerer großer Gesäßmuskel",
    "gluteus_maximus.lower": "Unterer großer Gesäßmuskel",
    "quadriceps.rectus_femoris": "Gerader Oberschenkelmuskel",
    "quadriceps.vastus_lateralis": "Äußerer breiter Oberschenkelmuskel",
    "quadriceps.vastus_medialis": "Innerer breiter Oberschenkelmuskel",
    "adductors.anterior_region": "Vordere Adduktoren",
    "adductors.posterior_region": "Hintere Adduktoren",
    "hamstrings.biceps_femoris_long_head": "Langer Kopf des Beinbizeps",
    "hamstrings.biceps_femoris_short_head": "Kurzer Kopf des Beinbizeps",
    "hamstrings.semitendinosus": "Halbsehnenmuskel",
    "hamstrings.semimembranosus": "Halbmembranmuskel",
    "lower_leg.tibialis_anterior": "Vorderer Schienbeinmuskel",
    "lower_leg.fibularis": "Wadenbeinmuskeln",
    "calf.gastrocnemius_medial": "Innerer Zwillingswadenmuskel",
    "calf.gastrocnemius_lateral": "Äußerer Zwillingswadenmuskel",
    "calf.soleus": "Schollenmuskel"
  },
  ar: {
    "neck.sternocleidomastoid": "العضلة القصية الترقوية الخشائية",
    "trapezius.upper": "شبه المنحرفة العلوية",
    "trapezius.middle": "شبه المنحرفة الوسطى",
    "trapezius.lower": "شبه المنحرفة السفلية",
    "deltoid.anterior": "الدالية الأمامية",
    "deltoid.lateral": "الدالية الجانبية",
    "deltoid.posterior": "الدالية الخلفية",
    "pectoralis.upper": "الصدر العلوي",
    "pectoralis.middle": "الصدر الأوسط",
    "pectoralis.lower": "الصدر السفلي",
    "pectoralis.outer": "الصدر الخارجي",
    "infraspinatus": "تحت الشوكة",
    "teres_minor": "المدورة الصغرى",
    "teres_major": "المدورة الكبرى",
    "latissimus.upper": "اللاتس العلوية",
    "latissimus.middle": "اللاتس الوسطى",
    "latissimus.lower": "اللاتس السفلية",
    "latissimus.outer": "اللاتس الخارجية",
    "serratus.anterior": "المنشارية الأمامية",
    "biceps.long_head": "الرأس الطويل للبايسبس",
    "biceps.short_head": "الرأس القصير للبايسبس",
    "brachialis": "العضدية",
    "triceps.long_head": "الرأس الطويل للترايسبس",
    "triceps.lateral_head": "الرأس الجانبي للترايسبس",
    "triceps.medial_head": "الرأس الإنسي للترايسبس",
    "brachioradialis": "العضدية الكعبرية",
    "forearm.pronator_teres": "الكابة المدورة",
    "forearm.flexor_mass": "قابضات الساعد",
    "forearm.extensor_mass": "باسطات الساعد",
    "rectus_abdominis.upper": "البطن العلوية",
    "rectus_abdominis.middle": "البطن الوسطى",
    "rectus_abdominis.lower": "البطن السفلية",
    "oblique.external_upper": "المائلة الخارجية العلوية",
    "oblique.external_lower": "المائلة الخارجية السفلية",
    "spinal_erectors.upper": "ناصبات العمود العلوية",
    "spinal_erectors.lower": "ناصبات العمود السفلية",
    "hip_flexors.anterior": "مثنيات الورك الأمامية",
    "tensor_fasciae_latae": "موترة اللفافة العريضة",
    "gluteus.medius": "الألوية الوسطى",
    "gluteus_maximus.upper": "الألوية الكبرى العلوية",
    "gluteus_maximus.middle": "الألوية الكبرى الوسطى",
    "gluteus_maximus.lower": "الألوية الكبرى السفلية",
    "quadriceps.rectus_femoris": "المستقيمة الفخذية",
    "quadriceps.vastus_lateralis": "الواسعة الوحشية",
    "quadriceps.vastus_medialis": "الواسعة الإنسية",
    "adductors.anterior_region": "المقربات الأمامية",
    "adductors.posterior_region": "المقربات الخلفية",
    "hamstrings.biceps_femoris_long_head": "الرأس الطويل لذات الرأسين الفخذية",
    "hamstrings.biceps_femoris_short_head": "الرأس القصير لذات الرأسين الفخذية",
    "hamstrings.semitendinosus": "نصف الوترية",
    "hamstrings.semimembranosus": "نصف الغشائية",
    "lower_leg.tibialis_anterior": "الظنبوبية الأمامية",
    "lower_leg.fibularis": "الشظوية",
    "calf.gastrocnemius_medial": "التوأمية الإنسية",
    "calf.gastrocnemius_lateral": "التوأمية الوحشية",
    "calf.soleus": "النعلية"
  }
};

const broadNames: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    pectoralis_major: "Chest", anterior_deltoid: "Anterior deltoid", lateral_deltoid: "Lateral deltoid", posterior_deltoid: "Posterior deltoid",
    trapezius: "Trapezius", latissimus_dorsi: "Latissimus dorsi", upper_back: "Upper back", biceps_brachii: "Biceps", triceps_brachii: "Triceps",
    forearms: "Forearms", rotator_cuff: "Rotator cuff", serratus_anterior: "Serratus anterior", rectus_abdominis: "Abdominals", obliques: "Obliques",
    erector_spinae: "Spinal erectors", gluteus_maximus: "Gluteus maximus", gluteus_medius: "Gluteus medius", quadriceps: "Quadriceps",
    hamstrings: "Hamstrings", adductors: "Adductors", hip_flexors: "Hip flexors", gastrocnemius: "Gastrocnemius", soleus: "Soleus", tibialis_anterior: "Tibialis anterior"
  },
  de: {
    pectoralis_major: "Brust", anterior_deltoid: "Vorderer Deltamuskel", lateral_deltoid: "Seitlicher Deltamuskel", posterior_deltoid: "Hinterer Deltamuskel",
    trapezius: "Trapezmuskel", latissimus_dorsi: "Latissimus", upper_back: "Oberer Rücken", biceps_brachii: "Bizeps", triceps_brachii: "Trizeps",
    forearms: "Unterarme", rotator_cuff: "Rotatorenmanschette", serratus_anterior: "Vorderer Sägemuskel", rectus_abdominis: "Bauchmuskeln", obliques: "Schräge Bauchmuskeln",
    erector_spinae: "Rückenstrecker", gluteus_maximus: "Großer Gesäßmuskel", gluteus_medius: "Mittlerer Gesäßmuskel", quadriceps: "Quadrizeps",
    hamstrings: "Beinbeuger", adductors: "Adduktoren", hip_flexors: "Hüftbeuger", gastrocnemius: "Zwillingswadenmuskel", soleus: "Schollenmuskel", tibialis_anterior: "Vorderer Schienbeinmuskel"
  },
  ar: {
    pectoralis_major: "الصدر", anterior_deltoid: "الدالية الأمامية", lateral_deltoid: "الدالية الجانبية", posterior_deltoid: "الدالية الخلفية",
    trapezius: "شبه المنحرفة", latissimus_dorsi: "العضلة الظهرية العريضة", upper_back: "أعلى الظهر", biceps_brachii: "البايسبس", triceps_brachii: "الترايسبس",
    forearms: "الساعدان", rotator_cuff: "الكفة المدورة", serratus_anterior: "المنشارية الأمامية", rectus_abdominis: "عضلات البطن", obliques: "العضلات المائلة",
    erector_spinae: "ناصبات العمود", gluteus_maximus: "الألوية الكبرى", gluteus_medius: "الألوية الوسطى", quadriceps: "العضلات الرباعية",
    hamstrings: "الخلفية للفخذ", adductors: "المقربات", hip_flexors: "مثنيات الورك", gastrocnemius: "التوأمية", soleus: "النعلية", tibialis_anterior: "الظنبوبية الأمامية"
  }
};

function targetIdFromTranslationKey(key: string): AdvancedMuscleTargetId | null {
  const match = /^train\.muscleAtlas\.targets\.(.+)\.name$/.exec(key);
  return match?.[1] && match[1] in targetNames.en ? match[1] as AdvancedMuscleTargetId : null;
}

export type MuscleIntelligenceCopy = (typeof copy)[SupportedLanguage];

export function getMuscleIntelligenceCopy(language: SupportedLanguage): MuscleIntelligenceCopy {
  return copy[language] ?? copy.en;
}

export function interpolateMuscleCopy(template: string, values: Record<string, string | number>): string {
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), template);
}

export function getMuscleHeatMapLabels(language: SupportedLanguage): MuscleHeatMapLabels {
  const text = getMuscleIntelligenceCopy(language);
  return {
    frontView: text.front,
    backView: text.back,
    loading: text.loading,
    empty: text.empty,
    partial: text.partial,
    unavailable: text.unavailable,
    error: text.error,
    noSelection: text.noSelection,
    close: text.close,
    detailedRegionalMappingUnavailable: text.detailUnavailable,
    additionalBroadMappedContributionIncluded: text.broadIncluded,
    heat: { none: text.none, light: text.light, moderate: text.moderate, high: text.high },
    previewRole: { primary: text.primary, co_primary: text.coPrimary, secondary: text.secondary, stabilizer: text.stabilizer, none: text.none },
    targetName: (key) => {
      const id = targetIdFromTranslationKey(key);
      return id ? targetNames[language][id] : key;
    },
    targetSubtitle: () => null,
    broadTargetName: (id) => broadNames[language][id] ?? id.replaceAll("_", " ")
  };
}
