import type { WorkoutHistorySessionDetailResponse } from "@/types/workout-history";

export function workoutReportFixture(
  overrides: Partial<WorkoutHistorySessionDetailResponse> = {},
): WorkoutHistorySessionDetailResponse {
  return {
    contractVersion: 1,
    activity: {
      contractVersion: 1,
      activityId: "activity-private-id",
      canonicalSessionId: "20000000-0000-4000-8000-000000000002",
      scheduledSessionId: "scheduled-private-id",
      userId: "11111111-1111-4111-8111-111111111111",
      sourceKind: "performed",
      lifecycle: "completed",
      title: "Push & Pull — Rücken تمرين",
      category: "strength",
      effectiveAt: "2026-08-05T18:30:00.000Z",
      startedAt: "2026-08-05T18:00:00.000Z",
      completedAt: "2026-08-05T18:45:00.000Z",
      skippedAt: null,
      cancelledAt: null,
      durationMinutes: 45,
      notes: "Controlled session note — ملاحظة محفوظة.",
      planId: "plan-private-id",
      planDayId: "plan-day-private-id",
      planWeekId: "plan-week-private-id",
      planSessionId: "plan-session-private-id",
      hasPerformedSets: true,
      hasMeaningfulPerformance: true,
      capabilities: {
        openDetails: true,
        showPerformedSets: true,
        showPlannedVsActual: true,
        showMuscleAnalysis: true,
        calculatePerformanceMetrics: true,
        calculateVerifiedRecords: true,
        repeatWorkout: true,
        correctSession: true,
        softDeleteSession: true,
      },
    },
    historyRevision: 3,
    summary: {
      exerciseCount: 2,
      completedSetCount: 3,
      reliableVolume: 2_400,
      verifiedRecordCount: 1,
    },
    snapshot: {
      id: "snapshot-private-id",
      schemaVersion: "v2",
      frozenAt: "2026-08-05T18:45:00.000Z",
    },
    exercises: [
      {
        identity: "global:private-exercise-id",
        exerciseId: "exercise-private-id",
        snapshotItemId: "snapshot-item-private-id",
        name: "Bench Press",
        plannedName: "Barbell Bench Press",
        state: "replaced",
        category: "strength",
        plannedSetCount: 3,
        performedSets: [
          {
            id: "set-private-id-1",
            setNumber: 1,
            reps: 8,
            weightKg: 80,
            completedAt: "2026-08-05T18:10:00.000Z",
            notes: "Strong but controlled.",
            setType: "working",
            rpe: 8,
            rir: 2,
            matchState: "matched",
            plannedSet: {
              id: "planned-private-id-1",
              setOrder: 1,
              setType: "working",
              targetMode: "range",
              sideMode: "bilateral",
              restSeconds: 90,
              tempoTarget: "3-1-1",
              targets: [
                {
                  metricKey: "repetitions",
                  side: "none",
                  targetMode: "range",
                  targetValue: null,
                  minimumValue: 8,
                  maximumValue: 10,
                },
              ],
            },
            metrics: [],
            segments: [],
            verifiedRecords: [
              {
                id: "record-private-id",
                recordType: "highest_load",
                currentValue: 80,
                previousValue: 75,
                unit: "kg",
                estimated: false,
              },
            ],
          },
          {
            id: "set-private-id-2",
            setNumber: 2,
            reps: 10,
            weightKg: 70,
            completedAt: "2026-08-05T18:15:00.000Z",
            notes: null,
            setType: "working",
            rpe: null,
            rir: 1,
            matchState: "unplanned",
            plannedSet: null,
            metrics: [],
            segments: [],
            verifiedRecords: [],
          },
        ],
        missingPlannedSets: [
          {
            id: "planned-private-id-3",
            setOrder: 3,
            setType: "working",
            targetMode: "range",
            sideMode: "bilateral",
            restSeconds: 90,
            tempoTarget: null,
            targets: [
              {
                metricKey: "repetitions",
                side: "none",
                targetMode: "range",
                targetValue: null,
                minimumValue: 8,
                maximumValue: 10,
              },
            ],
          },
        ],
      },
      {
        identity: "name:سحب أمامي",
        exerciseId: null,
        snapshotItemId: null,
        name: "سحب أمامي 60 kg",
        plannedName: null,
        state: "completed",
        category: null,
        plannedSetCount: 1,
        performedSets: [
          {
            id: "set-private-id-3",
            setNumber: 1,
            reps: 12,
            weightKg: 60,
            completedAt: "2026-08-05T18:25:00.000Z",
            notes: null,
            setType: "working",
            rpe: 7.5,
            rir: 2.5,
            matchState: "matched",
            plannedSet: null,
            metrics: [],
            segments: [],
            verifiedRecords: [],
          },
        ],
        missingPlannedSets: [],
      },
    ],
    timeline: [],
    notices: [],
    ...overrides,
  };
}


export function semanticWorkoutReportFixture(): WorkoutHistorySessionDetailResponse {
  const detail = workoutReportFixture();
  detail.activity.category = "cardio";
  detail.activity.title = "Tempo Session — جلسة Tempo";
  detail.exercises = [
    {
      identity: "semantic-fixture",
      exerciseId: null,
      snapshotItemId: null,
      name: "Assisted Sprint X1",
      plannedName: "Assisted Sprint Plan",
      state: "adjusted",
      category: "cardio",
      plannedSetCount: 3,
      performedSets: [
        {
          id: "semantic-set-1",
          setNumber: 1,
          reps: null,
          weightKg: null,
          completedAt: "2026-08-05T18:10:00.000Z",
          notes: "User note Latin 45 — ملاحظة",
          setType: "warmup",
          rpe: 5,
          rir: 4,
          matchState: "matched",
          plannedSet: {
            id: "semantic-planned-1",
            setOrder: 1,
            setType: "warmup",
            targetMode: "mixed",
            sideMode: "alternating",
            restSeconds: 30,
            tempoTarget: null,
            targets: [
              {
                metricKey: "duration_seconds",
                side: "none",
                targetMode: "range",
                targetValue: null,
                minimumValue: 30,
                maximumValue: 45,
              },
              {
                metricKey: "distance_meters",
                side: "right",
                targetMode: "exact",
                targetValue: 250,
                minimumValue: null,
                maximumValue: null,
              },
            ],
          },
          metrics: [
            { metricKey: "duration_seconds", side: "none", value: 42, unit: "seconds" },
            { metricKey: "distance_meters", side: "right", value: 240, unit: "meters" },
            { metricKey: "bodyweight_kg", side: "bilateral", value: 82, unit: "kg" },
            { metricKey: "assistance_load_kg", side: "left", value: 15, unit: "kg" },
          ],
          segments: [
            {
              id: "semantic-segment-1",
              segmentOrder: 1,
              segmentKind: "rest_pause",
              side: "right",
              metrics: [
                { metricKey: "rounds", side: "right", value: 2, unit: "count" },
              ],
            },
          ],
          verifiedRecords: [],
        },
        {
          id: "semantic-set-2",
          setNumber: 2,
          reps: 8,
          weightKg: 20,
          completedAt: "2026-08-05T18:20:00.000Z",
          notes: null,
          setType: "drop",
          rpe: 8,
          rir: 1,
          matchState: "matched",
          plannedSet: null,
          metrics: [],
          segments: [
            {
              id: "semantic-segment-2",
              segmentOrder: 1,
              segmentKind: "drop",
              side: "left",
              metrics: [
                { metricKey: "external_load_kg", side: "left", value: 12, unit: "kg" },
              ],
            },
          ],
          verifiedRecords: [],
        },
      ],
      missingPlannedSets: [
        {
          id: "semantic-missing-3",
          setOrder: 3,
          setType: "failure",
          targetMode: "amrap",
          sideMode: "bilateral",
          restSeconds: null,
          tempoTarget: null,
          targets: [
            {
              metricKey: "repetitions",
              side: "bilateral",
              targetMode: "amrap",
              targetValue: null,
              minimumValue: null,
              maximumValue: null,
            },
          ],
        },
      ],
    },
  ];
  detail.summary = {
    exerciseCount: 1,
    completedSetCount: 2,
    reliableVolume: null,
    verifiedRecordCount: 0,
  };
  return detail;
}
