import type { WorkoutHistorySessionDetailResponse } from "@/types/workout-history";

export function workoutReportFixture(
  overrides: Partial<WorkoutHistorySessionDetailResponse> = {},
): WorkoutHistorySessionDetailResponse {
  return {
    contractVersion: 1,
    activity: {
      contractVersion: 1,
      activityId: "activity-private-id",
      canonicalSessionId: "20000000-0000-4000-8000-000000000002",
      scheduledSessionId: "scheduled-private-id",
      userId: "11111111-1111-4111-8111-111111111111",
      sourceKind: "performed",
      lifecycle: "completed",
      title: "Push & Pull — Rücken تمرين",
      category: "strength",
      effectiveAt: "2026-08-05T18:30:00.000Z",
      startedAt: "2026-08-05T18:00:00.000Z",
      completedAt: "2026-08-05T18:45:00.000Z",
      skippedAt: null,
      cancelledAt: null,
      durationMinutes: 45,
      notes: "Controlled session note — ملاحظة محفوظة.",
      planId: "plan-private-id",
      planDayId: "plan-day-private-id",
      planWeekId: "plan-week-private-id",
      planSessionId: "plan-session-private-id",
      hasPerformedSets: true,
      hasMeaningfulPerformance: true,
      capabilities: {
        openDetails: true,
        showPerformedSets: true,
        showPlannedVsActual: true,
        showMuscleAnalysis: true,
        calculatePerformanceMetrics: true,
        calculateVerifiedRecords: true,
        repeatWorkout: true,
        correctSession: true,
        softDeleteSession: true,
      },
    },
    historyRevision: 3,
    summary: {
      exerciseCount: 2,
      completedSetCount: 3,
      reliableVolume: 2_400,
      verifiedRecordCount: 1,
    },
    snapshot: {
      id: "snapshot-private-id",
      schemaVersion: "v2",
      frozenAt: "2026-08-05T18:45:00.000Z",
    },
    exercises: [
      {
        identity: "global:private-exercise-id",
        exerciseId: "exercise-private-id",
        snapshotItemId: "snapshot-item-private-id",
        name: "Bench Press",
        plannedName: "Barbell Bench Press",
        state: "replaced",
        category: "strength",
        plannedSetCount: 3,
        performedSets: [
          {
            id: "set-private-id-1",
            setNumber: 1,
            reps: 8,
            weightKg: 80,
            completedAt: "2026-08-05T18:10:00.000Z",
            notes: "Strong but controlled.",
            setType: "working",
            rpe: 8,
            rir: 2,
            matchState: "matched",
            plannedSet: {
              id: "planned-private-id-1",
              setOrder: 1,
              setType: "working",
              targetMode: "range",
              sideMode: "bilateral",
              restSeconds: 90,
              tempoTarget: "3-1-1",
              targets: [
                {
                  metricKey: "repetitions",
                  side: "none",
                  targetMode: "range",
                  targetValue: null,
                  minimumValue: 8,
                  maximumValue: 10,
                },
              ],
            },
            metrics: [],
            segments: [],
            verifiedRecords: [
              {
                id: "record-private-id",
                recordType: "highest_load",
                currentValue: 80,
                previousValue: 75,
                unit: "kg",
                estimated: false,
              },
            ],
          },
          {
            id: "set-private-id-2",
            setNumber: 2,
            reps: 10,
            weightKg: 70,
            completedAt: "2026-08-05T18:15:00.000Z",
            notes: null,
            setType: "working",
            rpe: null,
            rir: 1,
            matchState: "unplanned",
            plannedSet: null,
            metrics: [],
            segments: [],
            verifiedRecords: [],
          },
        ],
        missingPlannedSets: [
          {
            id: "planned-private-id-3",
            setOrder: 3,
            setType: "working",
            targetMode: "range",
            sideMode: "bilateral",
            restSeconds: 90,
            tempoTarget: null,
            targets: [
              {
                metricKey: "repetitions",
                side: "none",
                targetMode: "range",
                targetValue: null,
                minimumValue: 8,
                maximumValue: 10,
              },
            ],
          },
        ],
      },
      {
        identity: "name:سحب أمامي",
        exerciseId: null,
        snapshotItemId: null,
        name: "سحب أمامي 60 kg",
        plannedName: null,
        state: "completed",
        category: null,
        plannedSetCount: 1,
        performedSets: [
          {
            id: "set-private-id-3",
            setNumber: 1,
            reps: 12,
            weightKg: 60,
            completedAt: "2026-08-05T18:25:00.000Z",
            notes: null,
            setType: "working",
            rpe: 7.5,
            rir: 2.5,
            matchState: "matched",
            plannedSet: null,
            metrics: [],
            segments: [],
            verifiedRecords: [],
          },
        ],
        missingPlannedSets: [],
      },
    ],
    timeline: [],
    notices: [],
    ...overrides,
  };
}
