import { task, text, type TaskContract } from "@/lib/ai/prompt-contracts/types";
import type { PromptId } from "@/lib/ai/quick-prompts";

export const GROCERY_RECOVERY_CONTRACTS = {
  "build-grocery-list": task(["date", "meal_plan"], text("Derive ingredients from the saved meal plan, combine compatible units, and do not invent missing quantities.", "Leite Zutaten aus dem gespeicherten Mahlzeitenplan ab, kombiniere kompatible Einheiten und erfinde keine fehlenden Mengen.", "استخرج المكونات من خطة الوجبات المحفوظة واجمع الوحدات المتوافقة ولا تخترع كميات مفقودة."), [text("Deduplicated ingredient-level list", "Deduplizierte Einkaufsliste auf Zutatenebene", "قائمة مكونات دون تكرار"), text("Quantities and units where known", "Mengen und Einheiten, wenn bekannt", "الكميات والوحدات عند معرفتها"), text("Items needing quantity clarification", "Artikel mit unklarer Menge", "العناصر التي تحتاج توضيح الكمية"), text("Store-section grouping", "Gruppierung nach Ladenbereichen", "التجميع حسب أقسام المتجر")]),
  "review-grocery-list": task(["date", "grocery", "meal_plan"], text("Compare the saved list with the saved plan and do not mark uncertain pantry items as already owned.", "Vergleiche die gespeicherte Liste mit dem gespeicherten Plan und markiere unsichere Vorräte nicht als vorhanden.", "قارن القائمة المحفوظة بالخطة المحفوظة ولا تعتبر عناصر المخزن غير المؤكدة موجودة بالفعل."), [text("Duplicates", "Duplikate", "العناصر المكررة"), text("Missing ingredients", "Fehlende Zutaten", "المكونات الناقصة"), text("Quantity problems and unit inconsistency", "Mengenprobleme und uneinheitliche Einheiten", "مشاكل الكمية وعدم اتساق الوحدات"), text("Pantry opportunities and final corrections", "Vorratsmöglichkeiten und endgültige Korrekturen", "فرص استخدام الموجود والتصحيحات النهائية")]),
  "reduce-grocery-cost": task(["date", "grocery", "meal_plan", "nutrition_targets", "profile_nutrition_preferences"], text("Suggest cost changes as estimates, preserve nutrition intent, and identify items that should not be substituted.", "Kennzeichne Kosteneffekte als Schätzungen, erhalte den Ernährungszweck und nenne Artikel, die nicht ersetzt werden sollten.", "قدّم تأثير التكلفة كتقدير وحافظ على الهدف الغذائي وحدد العناصر التي لا ينبغي استبدالها."), [text("Expensive items or cost drivers", "Teure Artikel oder Kostentreiber", "العناصر المكلفة أو عوامل التكلفة"), text("Lower-cost alternatives", "Günstigere Alternativen", "بدائل أقل تكلفة"), text("Estimated cost and nutrition impact", "Geschätzte Kosten- und Ernährungswirkung", "التأثير التقديري على التكلفة والتغذية"), text("Items that should not be substituted", "Artikel, die nicht ersetzt werden sollten", "العناصر التي لا ينبغي استبدالها")]),
  "group-grocery-sections": task(["grocery"], text("Preserve item names and quantities while resolving duplicates before grouping.", "Erhalte Artikelnamen und Mengen und löse Duplikate vor der Gruppierung auf.", "حافظ على أسماء العناصر وكمياتها وحلّ التكرار قبل التجميع."), [text("Produce", "Obst und Gemüse", "الخضروات والفواكه"), text("Meat and protein, dairy, grains, pantry, and frozen", "Fleisch und Protein, Milchprodukte, Getreide, Vorrat und Tiefkühl", "اللحوم والبروتين والألبان والحبوب والمخزن والمجمّدات"), text("Other items", "Sonstige Artikel", "العناصر الأخرى"), text("Resolved duplicates", "Aufgelöste Duplikate", "العناصر المكررة بعد حلها")]),
  "review-recovery": task(["date", "workout_state", "recovery", "wellness"], text("Separate tracked sleep or fatigue evidence from interpretation and make no diagnosis.", "Trenne aufgezeichnete Schlaf- oder Müdigkeitsdaten von der Interpretation und stelle keine Diagnose.", "افصل بيانات النوم أو الإرهاق المسجلة عن التفسير ولا تشخّص."), [text("Known recovery evidence", "Bekannte Erholungsdaten", "بيانات التعافي المعروفة"), text("Tracking gaps and uncertainty", "Tracking-Lücken und Unsicherheit", "فجوات التتبع وعدم اليقين"), text("Practical non-medical interpretation", "Praktische nichtmedizinische Interpretation", "تفسير عملي غير طبي"), text("Small recovery and training actions", "Kleine Erholungs- und Trainingsmaßnahmen", "إجراءات صغيرة للتعافي والتدريب")]),
  "train-today": task(["date", "workout_state", "recovery", "wellness"], text("Use cautious readiness evidence and include a non-medical caution when information is limited or concerning.", "Nutze Bereitschaftsdaten vorsichtig und ergänze bei begrenzten oder auffälligen Informationen einen nichtmedizinischen Hinweis.", "استخدم بيانات الاستعداد بحذر وأضف تنبيهًا غير طبي عند محدودية المعلومات أو وجود ما يدعو للقلق."), [text("Known recovery evidence and schedule", "Bekannte Erholungsdaten und Zeitplan", "بيانات التعافي والجدول المعروفان"), text("Uncertainty", "Unsicherheit", "عدم اليقين"), text("Train, modify, or rest recommendation", "Empfehlung: trainieren, anpassen oder pausieren", "توصية: تمرين أو تعديل أو راحة"), text("Reason and non-medical caution", "Begründung und nichtmedizinischer Hinweis", "السبب والتنبيه غير الطبي")]),
  "reduce-stress": task(["date", "wellness"], text("Offer small non-medical actions and do not infer a mental-health diagnosis from fitness tracking.", "Biete kleine nichtmedizinische Maßnahmen an und leite aus Fitness-Tracking keine psychische Diagnose ab.", "اقترح إجراءات صغيرة غير طبية ولا تستنتج تشخيصًا نفسيًا من تتبع اللياقة."), [text("Current tracked evidence", "Aktuelle Tracking-Daten", "البيانات المتتبعة الحالية"), text("Two or three small actions", "Zwei oder drei kleine Maßnahmen", "إجراءان أو ثلاثة إجراءات صغيرة"), text("Estimated effort or time", "Geschätzter Aufwand oder Zeitbedarf", "الجهد أو الوقت التقديري"), text("One immediate action", "Eine sofortige Maßnahme", "إجراء فوري واحد")]),
  "review-sleep": task(["date", "recovery"], text("Interpret sleep only as general fitness context and make no medical claim.", "Interpretiere Schlaf nur als allgemeinen Fitnesskontext und stelle keine medizinische Behauptung auf.", "فسّر النوم كسياق عام للياقة فقط ولا تقدّم ادعاءً طبيًا."), [text("Known sleep duration and pattern", "Bekannte Schlafdauer und Muster", "مدة النوم ونمطه المعروفان"), text("Tracking gaps", "Tracking-Lücken", "فجوات التتبع"), text("Practical interpretation", "Praktische Interpretation", "تفسير عملي"), text("One small sleep-habit recommendation", "Eine kleine Empfehlung zur Schlafgewohnheit", "توصية صغيرة واحدة لعادات النوم")]),
  "review-habits": task(["date", "wellness"], text("Review only tracked habit completion and do not infer motivation or character from missing records.", "Prüfe nur aufgezeichnete Gewohnheitserfüllung und leite aus fehlenden Daten weder Motivation noch Charakter ab.", "راجع إكمال العادات المسجل فقط ولا تستنتج الدافع أو الشخصية من السجلات المفقودة."), [text("Tracked habits and completion", "Getrackte Gewohnheiten und Erledigung", "العادات المتتبعة وإكمالها"), text("Consistent and missed patterns", "Konstante und verpasste Muster", "أنماط الالتزام والفوات"), text("Tracking gaps", "Tracking-Lücken", "فجوات التتبع"), text("One realistic habit improvement", "Eine realistische Gewohnheitsverbesserung", "تحسين واقعي واحد للعادات")]),
  "review-supplements": task(["date", "wellness"], text("Review adherence only; do not recommend dosage, treatment, or a new supplement.", "Prüfe nur die Umsetzung und empfehle weder Dosierung noch Behandlung oder ein neues Supplement.", "راجع الالتزام فقط ولا توصِ بجرعة أو علاج أو مكمل جديد."), [text("Taken and missed pattern", "Muster eingenommener und verpasster Einträge", "نمط المأخوذ والفائت"), text("Tracking gaps", "Tracking-Lücken", "فجوات التتبع"), text("Adherence summary", "Zusammenfassung der Umsetzung", "ملخص الالتزام"), text("One non-medical tracking improvement", "Eine nichtmedizinische Tracking-Verbesserung", "تحسين غير طبي واحد للتتبع")]),
} satisfies Partial<Record<PromptId, TaskContract>>;
