"use client";

import Link from "next/link";
import { ArrowLeft, Copy, ExternalLink, Loader2, Paperclip, RotateCcw, Search, ShieldAlert, ShieldCheck } from "lucide-react";
import { useMemo, type Dispatch, type ReactNode, type SetStateAction } from "react";
import { OpenAiBlossom } from "@/components/brand/openai-blossom";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/components/ui/toaster";
import { getPromptAvailability, PROMPT_CATEGORIES, type PromptCapability, type PromptCategory, type PromptHomeSections, type PromptLanguage, type QuickPromptContext, type QuickPromptDefinition } from "@/lib/ai/quick-prompts";
import { evaluatePromptPermission, getPromptPermissionLabel, type PromptPermissionEvaluation } from "@/lib/ai/prompt-permissions";
import { localizePrompt } from "@/lib/ai/prompt-runtime";
import type { PromptSurfaceView } from "@/components/ai/quick-chatgpt-provider";
import type { AiPermissionConfig, AiPermissionSettingsStatus } from "@/services/database/ai-permissions";
import type { useTodayTranslation } from "@/lib/i18n/today";
import { cn } from "@/lib/utils";

type TodayTranslator = ReturnType<typeof useTodayTranslation>["tt"];
const categoryKeys = { all: "categoryAll", training: "categoryTraining", nutrition: "categoryNutrition", grocery: "categoryGrocery", recovery: "categoryRecovery", progress: "categoryProgress", daily: "categoryDaily", profile: "categoryProfile" } as const;
export type QuickChatGptSurfaceProps = { open: boolean; onOpenChange: (open: boolean) => void; view: PromptSurfaceView; setView: Dispatch<SetStateAction<PromptSurfaceView>>; language: PromptLanguage; dir: "ltr" | "rtl"; tt: TodayTranslator; context: QuickPromptContext; homeSections: PromptHomeSections; libraryPrompts: QuickPromptDefinition[]; librarySearch: string; setLibrarySearch: (value: string) => void; libraryCategory: PromptCategory | "all"; setLibraryCategory: (value: PromptCategory | "all") => void; title: string; description: string; editedPrompt: string; generatedPrompt: string; setEditedPrompt: (value: string) => void; attachmentExpected: boolean; contextChips: string[]; capability: PromptCapability; destination?: string; permissionEvaluation: PromptPermissionEvaluation; permissionUserId?: string | null; permissionLoading: boolean; permissionStatus: AiPermissionSettingsStatus | null; permissionConfig: AiPermissionConfig | null; missingSectionLabels: string; retryPermissions: () => void; copyError: boolean; setCopyError: (value: boolean) => void };

export function QuickChatGptSurface(props: QuickChatGptSurfaceProps) {
  const { toast } = useToast();
  const headerTitle = props.view.name === "home" ? props.tt("askChatGpt") : props.view.name === "library" ? props.tt("allChatGptPrompts") : props.title;
  const headerDescription = props.view.name === "home" ? props.tt("promptHomeDescription") : props.view.name === "library" ? props.tt("promptLibraryDescription") : props.description;
  function back() { if (props.view.name === "detail") props.setView(props.view.backTo === "library" ? { name: "library" } : { name: "home" }); else props.setView({ name: "home" }); }
  async function copyPrompt() { try { await navigator.clipboard.writeText(props.editedPrompt); props.setCopyError(false); toast({ title: props.tt("copied"), description: props.attachmentExpected ? props.tt("copiedPhoto") : props.tt("copiedNormal"), variant: "success" }); return true; } catch { props.setCopyError(true); toast({ title: props.tt("copyFailed"), variant: "error" }); return false; } }
  async function copyAndOpen() { const popup = window.open("about:blank", "_blank"); if (popup) popup.opener = null; const copied = await copyPrompt(); if (popup) popup.location.href = "https://chatgpt.com/"; else toast({ title: props.tt("popupBlocked"), variant: "error" }); if (copied && popup) props.onOpenChange(false); }
  return <Dialog open={props.open} onOpenChange={props.onOpenChange}><DialogContent variant="glass" layout="responsive-drawer" closeLabel={props.tt("close")} dir={props.dir}><DialogHeader className="mb-0 shrink-0 border-b border-border/70 px-5 py-4 text-start"><DialogTitle className="flex items-center gap-2"><OpenAiBlossom className="h-[22px] w-[22px]" />{headerTitle}</DialogTitle><DialogDescription>{headerDescription}</DialogDescription></DialogHeader><p className="sr-only" aria-live="polite">{props.view.name === "home" ? props.tt("promptHomeView") : props.view.name === "library" ? props.tt("promptLibraryView") : props.tt("promptDetailView")}</p><div className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-4 py-4 pb-[calc(env(safe-area-inset-bottom)+1.25rem)] lg:px-5">{props.view.name === "home" ? <HomeView {...props} /> : null}{props.view.name === "library" ? <LibraryView {...props} onBack={back} /> : null}{props.view.name === "detail" || props.view.name === "custom-detail" ? <DetailView {...props} onBack={back} onCopy={() => void copyPrompt()} onCopyAndOpen={() => void copyAndOpen()} /> : null}</div></DialogContent></Dialog>;
}
function HomeView(props: QuickChatGptSurfaceProps) { const select = (id: string) => props.setView({ name: "detail", promptId: id, backTo: "home" }); return <div className="space-y-6">{props.homeSections.recommended ? <Section title={props.tt("recommendedNow")}><PromptCard definition={props.homeSections.recommended} {...props} onSelect={() => select(props.homeSections.recommended!.id)} featured /></Section> : null}{props.homeSections.quick.length ? <Section title={props.tt("quickPromptList")}><div className="grid gap-2">{props.homeSections.quick.map((prompt) => <PromptCard key={prompt.id} definition={prompt} {...props} onSelect={() => select(prompt.id)} />)}</div></Section> : null}{props.homeSections.dynamic.length ? <Section title={props.tt("dynamicPrompts")}><div className="grid gap-2">{props.homeSections.dynamic.map((prompt) => <PromptCard key={prompt.id} definition={prompt} {...props} onSelect={() => select(prompt.id)} />)}</div></Section> : null}{!props.homeSections.recommended && !props.homeSections.quick.length && !props.homeSections.dynamic.length ? <p className="text-sm text-muted-foreground">{props.tt("noPrompts")}</p> : null}<Button type="button" variant="outline" className="min-h-12 w-full" onClick={() => props.setView({ name: "library" })}>{props.tt("browseAllPrompts")}</Button></div>; }
function LibraryView(props: QuickChatGptSurfaceProps & { onBack: () => void }) { const grouped = useMemo(() => PROMPT_CATEGORIES.map((category) => ({ category, prompts: props.libraryPrompts.filter((prompt) => prompt.category === category) })).filter((group) => group.prompts.length), [props.libraryPrompts]); return <div className="space-y-5"><Button type="button" variant="ghost" size="sm" onClick={props.onBack} className="min-h-11"><ArrowLeft className="h-4 w-4 rtl:rotate-180" />{props.tt("back")}</Button><label className="relative block"><span className="sr-only">{props.tt("searchPrompts")}</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground rtl:left-auto rtl:right-3" /><input type="search" value={props.librarySearch} onChange={(event) => props.setLibrarySearch(event.target.value)} placeholder={props.tt("searchPrompts")} className="min-h-12 w-full rounded-[14px] border border-border bg-card py-2 pl-10 pr-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring rtl:pl-3 rtl:pr-10" /></label><div className="flex gap-2 overflow-x-auto pb-1" role="toolbar" aria-label={props.tt("promptCategories")}>{(["all", ...PROMPT_CATEGORIES] as const).map((item) => <button key={item} type="button" aria-pressed={props.libraryCategory === item} onClick={() => props.setLibraryCategory(item)} className={cn("min-h-11 shrink-0 rounded-full border px-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", props.libraryCategory === item ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-muted-foreground hover:text-foreground")}>{props.tt(categoryKeys[item])}</button>)}</div>{grouped.map((group) => <section key={group.category}><h3 className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">{props.tt(categoryKeys[group.category])}</h3><div className="grid gap-2">{group.prompts.map((prompt) => <PromptCard key={prompt.id} definition={prompt} {...props} onSelect={() => props.setView({ name: "detail", promptId: prompt.id, backTo: "library" })} library />)}</div></section>)}{!props.libraryPrompts.length ? <p className="rounded-[14px] border border-border/70 p-4 text-sm text-muted-foreground">{props.tt("noMatchingPrompts")}</p> : null}</div>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section><h3 className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">{title}</h3>{children}</section>; }
function PromptCard(props: QuickChatGptSurfaceProps & { definition: QuickPromptDefinition; onSelect: () => void; featured?: boolean; library?: boolean }) { const localized = localizePrompt(props.definition, props.language); const availability = getPromptAvailability(props.definition, props.context, props.language); const permission = evaluatePromptPermission({ userId: props.permissionUserId, loading: props.permissionLoading, status: props.permissionStatus, config: props.permissionConfig, sections: props.definition.permissionSections, capability: props.definition.capability }); const status = !availability.available ? `${props.tt("requiresContext")}: ${availability.missingContext.join(", ")}` : getPromptPermissionLabel(permission, props.language); const warning = !availability.available || ["missing", "failed", "signed-out"].includes(permission.state); return <button type="button" onClick={props.onSelect} disabled={!availability.available} className={cn("w-full rounded-[16px] border p-3 text-start transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-60", props.featured ? "border-primary/35 bg-primary/5" : "border-border/70 bg-card hover:border-primary/35", props.library && "p-4")}><span className="flex items-start justify-between gap-3"><span className="min-w-0"><span className="font-semibold">{localized.title}</span><span className="mt-1 block text-sm text-muted-foreground">{localized.description}</span></span>{props.definition.attachmentExpected ? <Paperclip className="h-4 w-4 shrink-0" aria-label={props.tt("attachmentRequired")} /> : null}</span><span className="mt-2 flex flex-wrap gap-2 text-xs"><span className="rounded-full border px-2 py-1">{props.definition.capability === "write" ? props.tt("capabilityWrite") : props.tt("capabilityRead")}</span><span className={cn("rounded-full border px-2 py-1", warning ? "text-warning" : "text-primary")}>{status}</span></span></button>; }
function DetailView(props: QuickChatGptSurfaceProps & { onBack: () => void; onCopy: () => void; onCopyAndOpen: () => void }) { return <div className="space-y-4"><Button type="button" variant="ghost" size="sm" onClick={props.onBack} className="min-h-11"><ArrowLeft className="h-4 w-4 rtl:rotate-180" />{props.tt("back")}</Button>{props.attachmentExpected ? <p className="rounded-[14px] border border-primary/25 bg-primary/5 p-3 text-sm text-muted-foreground">{props.tt("photoInstruction")}</p> : null}<div className="space-y-2"><label htmlFor="quick-chatgpt-prompt" className="text-sm font-semibold">{props.tt("prompt")}</label><textarea id="quick-chatgpt-prompt" value={props.editedPrompt} onChange={(event) => props.setEditedPrompt(event.target.value)} rows={14} className="min-h-72 w-full resize-y rounded-[16px] border border-border bg-card px-3 py-3 text-sm leading-6 outline-none focus-visible:ring-2 focus-visible:ring-ring" /></div>{props.contextChips.length ? <div><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{props.tt("uses")}</p><div className="flex flex-wrap gap-2">{props.contextChips.map((chip) => <span key={chip} className="rounded-full border px-2.5 py-1 text-xs">{chip}</span>)}</div></div> : null}<PermissionState {...props} />{props.copyError ? <p role="alert" className="rounded-[14px] border border-destructive/30 bg-destructive/5 p-3 text-sm">{props.tt("copyFailed")}</p> : null}<div className="grid gap-2 sm:grid-cols-2"><Button type="button" variant="outline" onClick={props.onCopy} disabled={!props.editedPrompt.trim()} className="min-h-12"><Copy className="h-4 w-4" />{props.tt("copyOnly")}</Button><Button type="button" onClick={props.onCopyAndOpen} disabled={!props.editedPrompt.trim()} className="min-h-12"><ExternalLink className="h-4 w-4" />{props.tt("copyAndOpen")}</Button></div><Button type="button" variant="ghost" size="sm" onClick={() => props.setEditedPrompt(props.generatedPrompt)} disabled={props.editedPrompt === props.generatedPrompt} className="min-h-11"><RotateCcw className="h-4 w-4" />{props.tt("resetPrompt")}</Button></div>; }
function PermissionState(props: QuickChatGptSurfaceProps) { const state = props.permissionEvaluation; return <div className="rounded-[14px] border border-border/70 bg-muted/20 p-3 text-sm">{state.state === "loading" ? <p className="flex items-center gap-2"><Loader2 className="h-4 w-4 animate-spin" />{getPromptPermissionLabel(state, props.language)}</p> : state.state === "failed" ? <div className="space-y-2"><p className="flex gap-2 text-destructive"><ShieldAlert className="h-4 w-4" />{props.tt("permissionLoadFailed")}</p><Button type="button" size="sm" variant="outline" onClick={props.retryPermissions}>{props.tt("retry")}</Button></div> : state.state === "signed-out" ? <p className="flex gap-2 text-warning"><ShieldAlert className="h-4 w-4" />{getPromptPermissionLabel(state, props.language)}</p> : state.state === "missing" ? <div className="flex flex-wrap items-center justify-between gap-2"><p className="flex gap-2 text-warning"><ShieldAlert className="h-4 w-4" />{props.tt("accessRequired", { section: props.missingSectionLabels })}</p><Button asChild size="sm" variant="outline"><Link href="/settings/connections/chatgpt">{props.tt("reviewAccess")}</Link></Button></div> : <p className="flex gap-2 text-muted-foreground"><ShieldCheck className="h-4 w-4 text-primary" />{props.capability === "write" ? props.tt("writeCapable", { destination: props.destination ?? "Plaivra" }) : props.tt("readOnly")}</p>}</div>; }
