export {
  addCustomFoodLog,
  addCustomMealToLog,
  addCustomMealToMealPlan,
  addFoodToMealPlan,
  addGlobalFoodToToday,
  addWaterLog,
  copyYesterdaysMeals,
  createFoodKitchen,
  createFoodSubcategory,
  deleteCustomMeal,
  deleteFoodLog,
  deleteMealPlanItem,
  deleteUserFood,
  deleteWaterLog,
  egyptianFoodKitchenName,
  egyptianFoodSubcategories,
  getCalorieTargets,
  getCustomMeals,
  getDefaultFoodCategories,
  getFoodCategories,
  getFoodKitchens,
  getFoodLibrary,
  getGlobalFoods,
  getNutritionWeek,
  getTodayFoodLogs,
  getTodayMealPlanItems,
  getUserFoods,
  getWaterLogs,
  markMealPlanItemDone,
  mealTypes,
  updateFoodLogQuantity,
  updateMealPlanItem,
  upsertCalorieTargets,
  upsertCustomMeal,
  upsertUserFood
} from "./legacy-repository";

export type { CustomMealInput, UserFoodInput } from "./legacy-repository";
