import { describe, expect, it } from "vitest";
import { buildPromptContextItems, buildRuntimePrompt, getBackingCapabilityStatus, getRuntimeContextChips, RUNTIME_QUICK_PROMPTS } from "@/lib/ai/prompt-runtime";
import { QUICK_PROMPTS, type QuickPromptContext } from "@/lib/ai/quick-prompts";
import { INTERNAL_AI_ACTION_NAMES, WRITE_CAPABLE_AI_ACTION_NAMES } from "@/lib/ai/action-registry";
import { MCP_PUBLIC_TOOL_NAMES, mcpTools } from "@/lib/mcp/tools";

const context: QuickPromptContext = { today: "2026-07-12", units: { energy: "kJ", liquid: "oz", weight: "lb" }, workout: { hasPlan: true, scheduled: true, active: true, completed: false, title: "Upper A", exerciseCount: 6, durationMinutes: 45, historyCount: 7 }, nutrition: { hasTargets: true, targetsState: "loaded", foodLogsState: "loaded", remainingCalories: -100, remainingProtein: 42, foodLogCount: 3, mealPlanCount: 8 }, grocery: { state: "loaded", itemCount: 11 }, hydration: { state: "loaded", hasTarget: true, logCount: 3, remainingMl: 1183 }, recovery: { state: "loaded", hasData: true, sleepHours: 6.5, poorRecovery: true }, wellness: { state: "loaded", habitCount: 3, supplementCount: 2 }, progress: { state: "loaded", entryCount: 4 }, profile: { state: "loaded", hasGoals: true, hasTrainingPreferences: true, hasNutritionPreferences: true, hasConstraints: true }, selection: { exercise: "Seated Cable Row", meal: "Chicken rice bowl" } };

describe("prompt runtime correctness", () => {
  it("uses prompt-specific minimized context and the same source for chips", () => { const workout = QUICK_PROMPTS.find((item) => item.id === "adjust-today-workout")!; const photo = QUICK_PROMPTS.find((item) => item.id === "estimate-meal-photo")!; const workoutItems = buildPromptContextItems(workout, context, "en"); expect(workoutItems.some((item) => item.field === "workout")).toBe(true); expect(workoutItems.some((item) => item.field === "grocery")).toBe(false); expect(buildPromptContextItems(photo, context, "en")).toEqual([]); expect(getRuntimeContextChips(workout, context, "en")).toEqual(workoutItems.slice(0, 6).map((item) => `${item.label}: ${item.value}`)); });
  it("preserves negative macro balances and saved display units", () => { const macro = QUICK_PROMPTS.find((item) => item.id === "finish-macros")!; const prompt = buildRuntimePrompt(macro, context, "en"); expect(prompt).toContain("418 kJ above target"); expect(prompt).toContain("42 g remaining"); expect(prompt).not.toContain("0 kcal"); });
  it("keeps failed nutrition explicit instead of inventing zero", () => { const macro = QUICK_PROMPTS.find((item) => item.id === "finish-macros")!; const failed: QuickPromptContext = { ...context, nutrition: { ...context.nutrition!, foodLogsState: "failed", remainingCalories: null, remainingProtein: null } }; expect(buildPromptContextItems(macro, failed, "en")).toContainEqual(expect.objectContaining({ label: "Food logs", value: "unavailable" })); expect(buildRuntimePrompt(macro, failed, "en")).not.toMatch(/0 kcal|0 g remaining/); });
  it.each(["en", "de", "ar"] as const)("localizes status words and task contracts in %s", (language) => { const prompt = QUICK_PROMPTS.find((item) => item.id === "adjust-today-workout")!; const body = buildRuntimePrompt(prompt, context, language); expect(body).toContain(language === "de" ? "Aufgabenspezifische erwartete Ausgabe" : language === "ar" ? "المخرجات المطلوبة الخاصة بالمهمة" : "Task-specific required output"); if (language === "de") { expect(body).toContain("aktiv"); expect(body).not.toMatch(/Workout state: active/); } if (language === "ar") { expect(body).toContain("نشط"); expect(body).not.toMatch(/Workout state|active|remaining/); } });
  it("uses materially different output contracts for different tasks", () => { expect(buildRuntimePrompt(QUICK_PROMPTS.find((item) => item.id === "create-workout-plan")!, context, "en")).toContain("Weekly structure and training days"); expect(buildRuntimePrompt(QUICK_PROMPTS.find((item) => item.id === "replace-exercise")!, context, "en")).toContain("Two or three suitable alternatives"); expect(buildRuntimePrompt(QUICK_PROMPTS.find((item) => item.id === "estimate-meal-photo")!, context, "en")).toContain("Reasonable range and confidence"); });
  it("derives backing support from real runtime registries", () => { const realNames = new Set([...MCP_PUBLIC_TOOL_NAMES, ...mcpTools.map((tool) => tool.name), ...INTERNAL_AI_ACTION_NAMES]); const writeNames = new Set([...mcpTools.filter((tool) => !tool.annotations.readOnlyHint).map((tool) => tool.name), ...WRITE_CAPABLE_AI_ACTION_NAMES]); expect(RUNTIME_QUICK_PROMPTS.length).toBeGreaterThan(0); for (const prompt of RUNTIME_QUICK_PROMPTS) { const status = getBackingCapabilityStatus(prompt); expect(status.supported).toBe(true); expect(status.real.some((name) => realNames.has(name))).toBe(true); if (prompt.capability === "write") expect(status.write.some((name) => writeNames.has(name))).toBe(true); } });
});
