"use client";

import { useCallback } from "react";
import { useTranslation } from "@/lib/i18n/use-translation";

const en = {
  eat: "Eat", day: "Day", week: "Week", addFood: "Add food", askChatGpt: "Ask ChatGPT", previousDay: "Previous day", nextDay: "Next day",
  manage: "Manage", setTarget: "Set target", targetUnavailable: "Target unavailable", fallbackTarget: "Fallback target", trainingTarget: "Training-day target", restTarget: "Rest-day target", highActivityTarget: "High-activity target",
  calories: "Calories", protein: "Protein", carbs: "Carbs", fat: "Fat", consumed: "Consumed", target: "Target", remaining: "remaining", unavailable: "Unavailable", aboveTarget: "above target", targetHit: "Target reached",
  plannedNextMeal: "Planned next meal", markEaten: "Mark eaten", adjustFirst: "Adjust first", replace: "Replace", noPlannedMeal: "No relevant planned meal",
  repeatFood: "Repeat a food", viewAll: "View all", meal: "Meal", date: "Date", logging: "Logging…", logged: "Logged", retry: "Retry", loading: "Loading…",
  foodLog: "Food log", breakfast: "Breakfast", lunch: "Lunch", dinner: "Dinner", snacks: "Snacks", other: "Other", add: "Add", editFood: "Edit food log", saveChanges: "Save changes", delete: "Delete", notes: "Notes", quantity: "Quantity", serving: "Serving",
  remainingToday: "Remaining today", suggestedNext: "Suggested next action", proteinDinner: "Choose a protein-focused next meal", balancedMeal: "Choose a balanced next meal", targetComplete: "Targets are covered for today", logToContinue: "Log food to calculate what remains",
  water: "Water", more: "More", hydrationUnavailable: "Hydration unavailable", waterShortcutSaving: "Saving {amount}…",
  addFoodTitle: "Add food", quickRepeat: "Quick repeat", searchFoods: "Search foods", savedMeals: "Saved meals", barcode: "Barcode", customFoodMeal: "Custom food or meal", photoEstimate: "Estimate meal from photo", copyDay: "Copy from another day", back: "Back", close: "Close",
  destination: "Logging destination", chooseMethod: "Choose a logging method", foodSearchPlaceholder: "Search foods", logFood: "Log food", addToPlan: "Add to meal plan", macroPreview: "Macro preview", storedServingOnly: "Stored serving", noFoods: "No foods found", noSavedMeals: "No saved meals yet", editSavedMeal: "Edit saved meal",
  allCategories: "All categories", quantityPositive: "Quantity must be greater than zero.", searchFailed: "Foods could not be loaded.", savedMealsFailed: "Saved meals could not be loaded.", customPreserved: "Your date, meal, and return route will be preserved.", photoPrivacy: "Plaivra does not upload or store the image. Attach it directly in ChatGPT and confirm before saving.", foodItemsCount: "{count} food items",
  sourceDate: "Source date", loadSource: "Load day", selectItems: "Select items", sourceEmpty: "No food found on this day", sourceFailed: "Could not load this day", duplicatesFound: "Some selected items already exist on the target day", copySelected: "Copy selected items", copiedCount: "{count} items copied",
  weekCoverage: "Tracking coverage", noWeekData: "No nutrition data this week", noWeekDataDesc: "Log food on at least one day to see nutrition trends.", daysLogged: "{count} of 7 days logged", averagesLogged: "Averages are based on logged days", caloriesTrend: "Calories trend", proteinTrend: "Protein trend", avgCalories: "Average calories on logged days", avgProtein: "Average protein on logged days", adherence: "Adherence", openReports: "Open full reports",
  previousWeek: "Previous week", nextWeek: "Next week", loggedIndicator: "Logged", calendarAverage: "Seven-day calendar average", macroContribution: "Macro calorie contribution", adherenceUnavailableTargets: "Adherence unavailable because daily targets could not be loaded.", adherenceNotConfigured: "Adherence is unavailable because no logged day has a configured target.", adherenceMatched: "{near} of {eligible} target-matched logged days were near target", targetCoveragePartial: "Adherence uses only logged days with a valid daily target.",
  loadingLogs: "Loading food logs…", logsFailed: "Food logs could not load", waterFailed: "Water could not load", targetsFailed: "Targets could not load", plannedFailed: "Planned meals could not load", repeatsFailed: "Repeat foods could not load", weekFailed: "Week data could not load",
  settingsTitle: "Nutrition targets", settingsDesc: "Manage day-type targets outside the daily Eat flow.", returnEat: "Return to Eat", fallbackEditor: "Fallback target", estimateTargets: "Estimate targets", previewEstimate: "Estimate preview", saveFallback: "Save fallback target", fromProfile: "From profile", fromOnboarding: "From onboarding", latestMeasurement: "Latest measurement",
  successSaved: "Saved successfully", saveFailed: "Could not save the change.", deleteConfirm: "Delete this food log?", deleteLinkedProtected: "This log completes a planned meal. Completed meal states are permanent, so edit the log instead of deleting it.", criticalConsistencyError: "The linked food log could not be kept consistent. Plaivra reloaded the food log and planned meals from the server. Review both before trying again.", linkedEditReloaded: "The latest food log and planned meal were reloaded.",
  cameraUnavailable: "Camera unavailable. Enter the barcode manually.", scan: "Scan", stop: "Stop", lookup: "Lookup", product: "Product", noNested: "All methods stay inside this Add Food surface.", barcodePlaceholder: "EAN / UPC / GTIN", productLoadFailed: "Product could not be loaded.", barcodeLookupFailed: "Barcode lookup failed.", openingCamera: "Opening camera…", cameraReady: "Camera ready.", reviewProductQuantity: "Review the product and quantity before logging.", productLogFailed: "Product could not be logged.",
  validationFoodName: "Food name is required.", validationServing: "Serving is required.", validationQuantity: "Quantity must be greater than zero.", validationEnergy: "Energy and macro values must be zero or higher.",
  partialTargetLoad: "Some target sources could not load. Available saved data remains editable.", activeTargetFor: "Active target for", automatic: "Automatic", edit: "Edit", notSaved: "Not saved", invalidEnergy: "Energy must be between {min} and {max} {unit}.", invalidValue: "Enter a realistic non-negative value.", invalidLiquid: "Water must be between {min} and {max} {unit}.", completeEstimator: "Enter age, height, and weight before estimating.", estimatedNote: "Estimated from the reviewed profile inputs.", reviewEstimate: "Review the estimated values before saving.", targetPrefill: "Inputs are prefilled from the canonical profile, onboarding, and latest saved weight when available.",
  age: "Age", heightCm: "Height (cm)", heightFeet: "Height (feet)", heightInches: "Height (inches)", weightKg: "Weight (kg)", weightLb: "Weight (lb)", sex: "Sex", activity: "Activity", goal: "Goal", estimateDisclaimer: "Estimated values are not saved until you choose an explicit action.", useTodayOnly: "Use for today only", saveTrainingTarget: "Save training-day target", copyFallback: "Copy to fallback target",
  male: "Male", female: "Female", sedentary: "Sedentary", light: "Light activity", moderate: "Moderate activity", veryActive: "Very active", fatLoss: "Fat loss", maintenance: "Maintenance", muscleGain: "Muscle gain", recomposition: "Body recomposition",
  foodBuilderTitle: "Food Builder", foodBuilderDescription: "Create or edit reusable foods and meals for {date}. Intended meal: {meal}.", foodBuilderAdminTitle: "Reusable food and meal administration", foodBuilderAdminDescription: "Normal logging and food search stay in Eat. This route only protects larger custom-food and saved-meal drafts.", backToEat: "Back to Eat", closeBuilder: "Close builder", openBuilder: "Create or edit custom foods and meals", discardBuilderTitle: "Discard custom nutrition draft?", discardBuilderDescription: "Your unsaved custom food or saved meal changes will remain on screen unless you discard them.", discardBuilderConfirm: "Discard and close", keepEditing: "Keep editing", builderLoadingDescription: "Custom foods and saved meals are loading."
} as const;

export type EatKey = keyof typeof en;
type EatDictionary = Record<EatKey, string>;

const de: EatDictionary = {
  eat: "Essen", day: "Tag", week: "Woche", addFood: "Lebensmittel hinzufügen", askChatGpt: "ChatGPT fragen", previousDay: "Vorheriger Tag", nextDay: "Nächster Tag",
  manage: "Verwalten", setTarget: "Ziel festlegen", targetUnavailable: "Ziel nicht verfügbar", fallbackTarget: "Fallback-Ziel", trainingTarget: "Trainingstag-Ziel", restTarget: "Ruhetag-Ziel", highActivityTarget: "Ziel für hohe Aktivität",
  calories: "Kalorien", protein: "Protein", carbs: "Kohlenhydrate", fat: "Fett", consumed: "Verbraucht", target: "Ziel", remaining: "verbleibend", unavailable: "Nicht verfügbar", aboveTarget: "über dem Ziel", targetHit: "Ziel erreicht",
  plannedNextMeal: "Nächste geplante Mahlzeit", markEaten: "Als gegessen markieren", adjustFirst: "Zuerst anpassen", replace: "Ersetzen", noPlannedMeal: "Keine relevante geplante Mahlzeit",
  repeatFood: "Lebensmittel wiederholen", viewAll: "Alle anzeigen", meal: "Mahlzeit", date: "Datum", logging: "Wird protokolliert…", logged: "Protokolliert", retry: "Erneut versuchen", loading: "Wird geladen…",
  foodLog: "Ernährungsprotokoll", breakfast: "Frühstück", lunch: "Mittagessen", dinner: "Abendessen", snacks: "Snacks", other: "Sonstiges", add: "Hinzufügen", editFood: "Eintrag bearbeiten", saveChanges: "Änderungen speichern", delete: "Löschen", notes: "Notizen", quantity: "Menge", serving: "Portion",
  remainingToday: "Heute verbleibend", suggestedNext: "Empfohlene nächste Aktion", proteinDinner: "Wähle als Nächstes eine proteinreiche Mahlzeit", balancedMeal: "Wähle als Nächstes eine ausgewogene Mahlzeit", targetComplete: "Die heutigen Ziele sind abgedeckt", logToContinue: "Lebensmittel protokollieren, um den Rest zu berechnen",
  water: "Wasser", more: "Mehr", hydrationUnavailable: "Wasserdaten nicht verfügbar", waterShortcutSaving: "{amount} werden gespeichert…",
  addFoodTitle: "Lebensmittel hinzufügen", quickRepeat: "Schnell wiederholen", searchFoods: "Lebensmittel suchen", savedMeals: "Gespeicherte Mahlzeiten", barcode: "Barcode", customFoodMeal: "Eigenes Lebensmittel oder Mahlzeit", photoEstimate: "Mahlzeit aus Foto schätzen", copyDay: "Von anderem Tag kopieren", back: "Zurück", close: "Schließen",
  destination: "Ziel der Protokollierung", chooseMethod: "Methode auswählen", foodSearchPlaceholder: "Lebensmittel suchen", logFood: "Lebensmittel protokollieren", addToPlan: "Zum Mahlzeitenplan", macroPreview: "Makro-Vorschau", storedServingOnly: "Gespeicherte Portion", noFoods: "Keine Lebensmittel gefunden", noSavedMeals: "Noch keine gespeicherten Mahlzeiten", editSavedMeal: "Gespeicherte Mahlzeit bearbeiten",
  allCategories: "Alle Kategorien", quantityPositive: "Die Menge muss größer als null sein.", searchFailed: "Lebensmittel konnten nicht geladen werden.", savedMealsFailed: "Gespeicherte Mahlzeiten konnten nicht geladen werden.", customPreserved: "Datum, Mahlzeit und Rücksprungziel bleiben erhalten.", photoPrivacy: "Plaivra lädt das Bild nicht hoch und speichert es nicht. Füge es direkt in ChatGPT an und bestätige vor dem Speichern.", foodItemsCount: "{count} Lebensmittel",
  sourceDate: "Quelldatum", loadSource: "Tag laden", selectItems: "Elemente auswählen", sourceEmpty: "An diesem Tag wurden keine Lebensmittel gefunden", sourceFailed: "Dieser Tag konnte nicht geladen werden", duplicatesFound: "Einige ausgewählte Elemente existieren bereits am Zieltag", copySelected: "Auswahl kopieren", copiedCount: "{count} Elemente kopiert",
  weekCoverage: "Tracking-Abdeckung", noWeekData: "Keine Ernährungsdaten in dieser Woche", noWeekDataDesc: "Protokolliere an mindestens einem Tag Lebensmittel, um Trends zu sehen.", daysLogged: "{count} von 7 Tagen protokolliert", averagesLogged: "Durchschnitte basieren auf protokollierten Tagen", caloriesTrend: "Kalorientrend", proteinTrend: "Proteintrend", avgCalories: "Durchschnittliche Energie an protokollierten Tagen", avgProtein: "Durchschnittliches Protein an protokollierten Tagen", adherence: "Zielnähe", openReports: "Vollständige Berichte öffnen",
  previousWeek: "Vorherige Woche", nextWeek: "Nächste Woche", loggedIndicator: "Protokolliert", calendarAverage: "Siebentägiger Kalenderdurchschnitt", macroContribution: "Kalorienbeitrag der Makros", adherenceUnavailableTargets: "Die Zielnähe ist nicht verfügbar, weil die Tagesziele nicht geladen werden konnten.", adherenceNotConfigured: "Die Zielnähe ist nicht verfügbar, weil kein protokollierter Tag ein konfiguriertes Ziel hat.", adherenceMatched: "{near} von {eligible} protokollierten Tagen mit Ziel lagen nahe am Ziel", targetCoveragePartial: "Die Zielnähe verwendet nur protokollierte Tage mit einem gültigen Tagesziel.",
  loadingLogs: "Ernährungsprotokolle werden geladen…", logsFailed: "Ernährungsprotokolle konnten nicht geladen werden", waterFailed: "Wasser konnte nicht geladen werden", targetsFailed: "Ziele konnten nicht geladen werden", plannedFailed: "Geplante Mahlzeiten konnten nicht geladen werden", repeatsFailed: "Wiederholbare Lebensmittel konnten nicht geladen werden", weekFailed: "Wochendaten konnten nicht geladen werden",
  settingsTitle: "Ernährungsziele", settingsDesc: "Verwalte Tagesziele außerhalb des täglichen Essen-Ablaufs.", returnEat: "Zurück zu Essen", fallbackEditor: "Fallback-Ziel", estimateTargets: "Ziele schätzen", previewEstimate: "Schätzvorschau", saveFallback: "Fallback-Ziel speichern", fromProfile: "Aus dem Profil", fromOnboarding: "Aus dem Onboarding", latestMeasurement: "Neueste Messung",
  successSaved: "Erfolgreich gespeichert", saveFailed: "Die Änderung konnte nicht gespeichert werden.", deleteConfirm: "Diesen Ernährungseintrag löschen?", deleteLinkedProtected: "Dieser Eintrag schließt eine geplante Mahlzeit ab. Abgeschlossene Zustände sind dauerhaft; bearbeite den Eintrag statt ihn zu löschen.", criticalConsistencyError: "Der verknüpfte Ernährungseintrag konnte nicht konsistent gehalten werden. Plaivra hat Ernährungsprotokoll und geplante Mahlzeiten neu vom Server geladen. Prüfe beide vor einem neuen Versuch.", linkedEditReloaded: "Der aktuelle Ernährungseintrag und die geplante Mahlzeit wurden neu geladen.",
  cameraUnavailable: "Kamera nicht verfügbar. Barcode manuell eingeben.", scan: "Scannen", stop: "Stoppen", lookup: "Suchen", product: "Produkt", noNested: "Alle Methoden bleiben in dieser Oberfläche.", barcodePlaceholder: "EAN / UPC / GTIN", productLoadFailed: "Das Produkt konnte nicht geladen werden.", barcodeLookupFailed: "Die Barcode-Suche ist fehlgeschlagen.", openingCamera: "Kamera wird geöffnet…", cameraReady: "Kamera ist bereit.", reviewProductQuantity: "Prüfe Produkt und Menge vor dem Protokollieren.", productLogFailed: "Das Produkt konnte nicht protokolliert werden.",
  validationFoodName: "Der Lebensmittelname ist erforderlich.", validationServing: "Eine Portion ist erforderlich.", validationQuantity: "Die Menge muss größer als null sein.", validationEnergy: "Energie- und Makrowerte müssen mindestens null sein.",
  partialTargetLoad: "Einige Zielquellen konnten nicht geladen werden. Verfügbare gespeicherte Daten bleiben bearbeitbar.", activeTargetFor: "Aktives Ziel für", automatic: "Automatisch", edit: "Bearbeiten", notSaved: "Nicht gespeichert", invalidEnergy: "Energie muss zwischen {min} und {max} {unit} liegen.", invalidValue: "Gib einen realistischen nichtnegativen Wert ein.", invalidLiquid: "Wasser muss zwischen {min} und {max} {unit} liegen.", completeEstimator: "Alter, Größe und Gewicht vor der Schätzung eingeben.", estimatedNote: "Aus den geprüften Profilwerten geschätzt.", reviewEstimate: "Prüfe die geschätzten Werte vor dem Speichern.", targetPrefill: "Eingaben werden aus Profil, Onboarding und dem neuesten gespeicherten Gewicht vorausgefüllt.",
  age: "Alter", heightCm: "Größe (cm)", heightFeet: "Größe (Fuß)", heightInches: "Größe (Zoll)", weightKg: "Gewicht (kg)", weightLb: "Gewicht (lb)", sex: "Geschlecht", activity: "Aktivität", goal: "Ziel", estimateDisclaimer: "Geschätzte Werte werden erst nach einer ausdrücklichen Aktion gespeichert.", useTodayOnly: "Nur für heute verwenden", saveTrainingTarget: "Trainingstag-Ziel speichern", copyFallback: "Zum Fallback-Ziel kopieren",
  male: "Männlich", female: "Weiblich", sedentary: "Sitzend", light: "Leichte Aktivität", moderate: "Mittlere Aktivität", veryActive: "Sehr aktiv", fatLoss: "Fettverlust", maintenance: "Gewicht halten", muscleGain: "Muskelaufbau", recomposition: "Körperrekomposition",
  foodBuilderTitle: "Lebensmittel-Builder", foodBuilderDescription: "Erstelle oder bearbeite wiederverwendbare Lebensmittel und Mahlzeiten für {date}. Vorgesehene Mahlzeit: {meal}.", foodBuilderAdminTitle: "Verwaltung wiederverwendbarer Lebensmittel und Mahlzeiten", foodBuilderAdminDescription: "Normales Protokollieren und die Lebensmittelsuche bleiben in Essen. Diese Route schützt nur umfangreichere Entwürfe für eigene Lebensmittel und gespeicherte Mahlzeiten.", backToEat: "Zurück zu Essen", closeBuilder: "Builder schließen", openBuilder: "Eigene Lebensmittel und Mahlzeiten erstellen oder bearbeiten", discardBuilderTitle: "Ernährungsentwurf verwerfen?", discardBuilderDescription: "Nicht gespeicherte Änderungen bleiben auf dem Bildschirm, bis du sie verwirfst.", discardBuilderConfirm: "Verwerfen und schließen", keepEditing: "Weiter bearbeiten", builderLoadingDescription: "Eigene Lebensmittel und gespeicherte Mahlzeiten werden geladen."
};

const ar: EatDictionary = {
  eat: "الأكل", day: "اليوم", week: "الأسبوع", addFood: "إضافة طعام", askChatGpt: "اسأل ChatGPT", previousDay: "اليوم السابق", nextDay: "اليوم التالي",
  manage: "إدارة", setTarget: "تحديد هدف", targetUnavailable: "الهدف غير متاح", fallbackTarget: "الهدف الاحتياطي", trainingTarget: "هدف يوم التمرين", restTarget: "هدف يوم الراحة", highActivityTarget: "هدف يوم النشاط العالي",
  calories: "السعرات", protein: "البروتين", carbs: "الكربوهيدرات", fat: "الدهون", consumed: "المستهلك", target: "الهدف", remaining: "متبقي", unavailable: "غير متاح", aboveTarget: "فوق الهدف", targetHit: "تم الوصول إلى الهدف",
  plannedNextMeal: "الوجبة المخططة التالية", markEaten: "تسجيلها كمأكولة", adjustFirst: "تعديل أولًا", replace: "استبدال", noPlannedMeal: "لا توجد وجبة مخططة مناسبة",
  repeatFood: "تكرار طعام", viewAll: "عرض الكل", meal: "الوجبة", date: "التاريخ", logging: "جارٍ التسجيل…", logged: "تم التسجيل", retry: "إعادة المحاولة", loading: "جارٍ التحميل…",
  foodLog: "سجل الطعام", breakfast: "الإفطار", lunch: "الغداء", dinner: "العشاء", snacks: "الوجبات الخفيفة", other: "أخرى", add: "إضافة", editFood: "تعديل سجل الطعام", saveChanges: "حفظ التغييرات", delete: "حذف", notes: "ملاحظات", quantity: "الكمية", serving: "الحصة",
  remainingToday: "المتبقي اليوم", suggestedNext: "الإجراء التالي المقترح", proteinDinner: "اختر وجبة تالية غنية بالبروتين", balancedMeal: "اختر وجبة تالية متوازنة", targetComplete: "تمت تغطية أهداف اليوم", logToContinue: "سجّل الطعام لحساب المتبقي",
  water: "المياه", more: "المزيد", hydrationUnavailable: "بيانات المياه غير متاحة", waterShortcutSaving: "جارٍ حفظ {amount}…",
  addFoodTitle: "إضافة طعام", quickRepeat: "تكرار سريع", searchFoods: "البحث عن طعام", savedMeals: "الوجبات المحفوظة", barcode: "الباركود", customFoodMeal: "طعام أو وجبة مخصصة", photoEstimate: "تقدير وجبة من صورة", copyDay: "نسخ من يوم آخر", back: "رجوع", close: "إغلاق",
  destination: "وجهة التسجيل", chooseMethod: "اختر طريقة التسجيل", foodSearchPlaceholder: "ابحث عن طعام", logFood: "تسجيل الطعام", addToPlan: "إضافة إلى خطة الوجبات", macroPreview: "معاينة الماكروز", storedServingOnly: "الحصة المحفوظة", noFoods: "لم يتم العثور على أطعمة", noSavedMeals: "لا توجد وجبات محفوظة", editSavedMeal: "تعديل الوجبة المحفوظة",
  allCategories: "كل الفئات", quantityPositive: "يجب أن تكون الكمية أكبر من صفر.", searchFailed: "تعذر تحميل الأطعمة.", savedMealsFailed: "تعذر تحميل الوجبات المحفوظة.", customPreserved: "سيتم الاحتفاظ بالتاريخ والوجبة ومسار الرجوع.", photoPrivacy: "لا يرفع Plaivra الصورة ولا يخزنها. أرفقها مباشرة في ChatGPT وراجع التقدير قبل الحفظ.", foodItemsCount: "عدد عناصر الطعام: {count}",
  sourceDate: "تاريخ المصدر", loadSource: "تحميل اليوم", selectItems: "اختر العناصر", sourceEmpty: "لا يوجد طعام مسجل في هذا اليوم", sourceFailed: "تعذر تحميل هذا اليوم", duplicatesFound: "بعض العناصر المحددة موجودة بالفعل في اليوم المستهدف", copySelected: "نسخ العناصر المحددة", copiedCount: "تم نسخ {count} عنصرًا",
  weekCoverage: "تغطية التتبع", noWeekData: "لا توجد بيانات تغذية هذا الأسبوع", noWeekDataDesc: "سجّل الطعام في يوم واحد على الأقل لرؤية اتجاهات التغذية.", daysLogged: "تم تسجيل {count} من 7 أيام", averagesLogged: "المتوسطات مبنية على الأيام المسجلة", caloriesTrend: "اتجاه الطاقة", proteinTrend: "اتجاه البروتين", avgCalories: "متوسط الطاقة في الأيام المسجلة", avgProtein: "متوسط البروتين في الأيام المسجلة", adherence: "الالتزام بالهدف", openReports: "فتح التقارير الكاملة",
  previousWeek: "الأسبوع السابق", nextWeek: "الأسبوع التالي", loggedIndicator: "تم التسجيل", calendarAverage: "متوسط الأيام السبعة", macroContribution: "مساهمة الماكروز في الطاقة", adherenceUnavailableTargets: "تعذر حساب الالتزام لأن أهداف الأيام لم تُحمّل.", adherenceNotConfigured: "تعذر حساب الالتزام لعدم وجود هدف صالح لأي يوم مسجل.", adherenceMatched: "كان {near} من أصل {eligible} أيام مسجلة ذات هدف قريبًا من الهدف", targetCoveragePartial: "يتم حساب الالتزام باستخدام الأيام المسجلة التي لها هدف يومي صالح فقط.",
  loadingLogs: "جارٍ تحميل سجلات الطعام…", logsFailed: "تعذر تحميل سجلات الطعام", waterFailed: "تعذر تحميل المياه", targetsFailed: "تعذر تحميل الأهداف", plannedFailed: "تعذر تحميل الوجبات المخططة", repeatsFailed: "تعذر تحميل الأطعمة القابلة للتكرار", weekFailed: "تعذر تحميل بيانات الأسبوع",
  settingsTitle: "أهداف التغذية", settingsDesc: "إدارة أهداف أنواع الأيام خارج مسار الأكل اليومي.", returnEat: "العودة إلى الأكل", fallbackEditor: "الهدف الاحتياطي", estimateTargets: "تقدير الأهداف", previewEstimate: "معاينة التقدير", saveFallback: "حفظ الهدف الاحتياطي", fromProfile: "من الملف الشخصي", fromOnboarding: "من الإعداد الأولي", latestMeasurement: "أحدث قياس",
  successSaved: "تم الحفظ بنجاح", saveFailed: "تعذر حفظ التغيير.", deleteConfirm: "هل تريد حذف سجل الطعام؟", deleteLinkedProtected: "هذا السجل يُكمل وجبة مخططة. حالات الوجبات المكتملة دائمة، لذلك عدّل السجل بدلًا من حذفه.", criticalConsistencyError: "تعذر الحفاظ على تطابق سجل الطعام مع الوجبة المرتبطة. أعاد Plaivra تحميل سجل الطعام والوجبات المخططة من الخادم. راجعهما قبل المحاولة مرة أخرى.", linkedEditReloaded: "تمت إعادة تحميل أحدث سجل طعام والوجبة المخططة.",
  cameraUnavailable: "الكاميرا غير متاحة. أدخل الباركود يدويًا.", scan: "مسح", stop: "إيقاف", lookup: "بحث", product: "المنتج", noNested: "كل الطرق داخل واجهة إضافة الطعام نفسها.", barcodePlaceholder: "EAN / UPC / GTIN", productLoadFailed: "تعذر تحميل المنتج.", barcodeLookupFailed: "فشل البحث بالباركود.", openingCamera: "جارٍ فتح الكاميرا…", cameraReady: "الكاميرا جاهزة.", reviewProductQuantity: "راجع المنتج والكمية قبل التسجيل.", productLogFailed: "تعذر تسجيل المنتج.",
  validationFoodName: "اسم الطعام مطلوب.", validationServing: "الحصة مطلوبة.", validationQuantity: "يجب أن تكون الكمية أكبر من صفر.", validationEnergy: "يجب ألا تقل قيم الطاقة والماكروز عن صفر.",
  partialTargetLoad: "تعذر تحميل بعض مصادر الأهداف. تظل البيانات المحفوظة المتاحة قابلة للتعديل.", activeTargetFor: "الهدف النشط ليوم", automatic: "تلقائي", edit: "تعديل", notSaved: "غير محفوظ", invalidEnergy: "يجب أن تكون الطاقة بين {min} و{max} {unit}.", invalidValue: "أدخل قيمة واقعية غير سالبة.", invalidLiquid: "يجب أن تكون المياه بين {min} و{max} {unit}.", completeEstimator: "أدخل العمر والطول والوزن قبل التقدير.", estimatedNote: "تم التقدير من بيانات الملف التي تمت مراجعتها.", reviewEstimate: "راجع القيم المقدرة قبل الحفظ.", targetPrefill: "يتم ملء المدخلات من الملف الشخصي والإعداد الأولي وأحدث وزن محفوظ عند توفره.",
  age: "العمر", heightCm: "الطول (سم)", heightFeet: "الطول (قدم)", heightInches: "الطول (بوصة)", weightKg: "الوزن (كجم)", weightLb: "الوزن (رطل)", sex: "الجنس", activity: "النشاط", goal: "الهدف", estimateDisclaimer: "لا يتم حفظ القيم المقدرة حتى تختار إجراءً صريحًا.", useTodayOnly: "استخدام لليوم فقط", saveTrainingTarget: "حفظ هدف يوم التمرين", copyFallback: "نسخ إلى الهدف الاحتياطي",
  male: "ذكر", female: "أنثى", sedentary: "قليل الحركة", light: "نشاط خفيف", moderate: "نشاط متوسط", veryActive: "نشاط مرتفع", fatLoss: "خسارة الدهون", maintenance: "الحفاظ على الوزن", muscleGain: "بناء العضلات", recomposition: "إعادة تشكيل الجسم",
  foodBuilderTitle: "منشئ الأطعمة", foodBuilderDescription: "أنشئ أو عدّل أطعمة ووجبات قابلة لإعادة الاستخدام لتاريخ {date}. الوجبة المقصودة: {meal}.", foodBuilderAdminTitle: "إدارة الأطعمة والوجبات القابلة لإعادة الاستخدام", foodBuilderAdminDescription: "يظل التسجيل العادي والبحث عن الطعام داخل صفحة الأكل. هذا المسار مخصص فقط لمسودات الأطعمة المخصصة والوجبات المحفوظة الأكبر.", backToEat: "العودة إلى الأكل", closeBuilder: "إغلاق المنشئ", openBuilder: "إنشاء أو تعديل أطعمة ووجبات مخصصة", discardBuilderTitle: "هل تريد تجاهل مسودة التغذية؟", discardBuilderDescription: "ستظل التغييرات غير المحفوظة على الشاشة حتى تختار تجاهلها.", discardBuilderConfirm: "تجاهل وإغلاق", keepEditing: "متابعة التعديل", builderLoadingDescription: "جارٍ تحميل الأطعمة المخصصة والوجبات المحفوظة."
};

export const eatDictionaries: Record<"en" | "de" | "ar", EatDictionary> = { en, de, ar };

export function useEatTranslation() {
  const { language, dir } = useTranslation();
  const locale = language === "de" ? "de-DE" : language === "ar" ? "ar-EG" : "en-GB";
  const et = useCallback((key: EatKey, values?: Record<string, string | number>): string => {
    const template = eatDictionaries[language][key];
    if (!values) return template;
    return Object.entries(values).reduce<string>((result, [name, item]) => result.replaceAll(`{${name}}`, String(item)), template);
  }, [language]);
  const formatDate = useCallback((value: string, options: Intl.DateTimeFormatOptions = { weekday: "long", day: "numeric", month: "long" }): string => new Intl.DateTimeFormat(locale, options).format(new Date(`${value}T12:00:00`)), [locale]);
  const mealLabel = useCallback((value: string): string => {
    const clean = value.toLowerCase();
    if (clean === "breakfast") return et("breakfast");
    if (clean === "lunch") return et("lunch");
    if (clean === "dinner") return et("dinner");
    if (clean === "snack" || clean === "snacks") return et("snacks");
    return et("other");
  }, [et]);
  return { language, dir, locale, et, formatDate, mealLabel };
}
