"use client";

import { useCallback } from "react";
import { useTranslation } from "@/lib/i18n/use-translation";
import type { SupportedLanguage } from "@/lib/i18n/types";

const en = {
  myWorkout: "My Workout", overviewDescription: "See what is next, follow your week, and keep your training plans organized.",
  askChatGpt: "Ask ChatGPT", createPlan: "Create plan", createWithChatGpt: "Create with ChatGPT", createManually: "Create manually",
  createFirstPlan: "Create your first training plan", createFirstPlanDescription: "Once saved, your plan appears here with direct editing, workout execution, history, and corrections.",
  today: "Today", todaysWorkout: "Today's workout", restDay: "Rest day", todayRestDay: "Today is a rest day", nextWorkout: "Next workout: {workout} on {weekday}", viewWeeklyPlan: "View weekly plan",
  exercises: "{count} exercises", aboutMinutes: "About {count} min", checkingStatus: "Checking status…", retryStatus: "Retry status", startWorkout: "Start workout", resumeWorkout: "Resume workout", viewCompletedWorkout: "View completed workout", skippedToday: "Skipped today", inProgress: "In progress", completed: "Completed", scheduled: "Scheduled", rest: "Rest",
  thisWeek: "This week", thisWeekDescription: "Your schedule at a glance. Start or resume only from Today above.", todayLabel: "Today", viewDay: "View day", moreExercises: "+ {count} more",
  activePlan: "Active plan", activePlanDescription: "This plan controls Today and your weekly schedule.", otherPlans: "Other plans", otherPlansDescription: "Alternatives stay compact until you need them.", archivedPlans: "Archived plans", archivedPlansDescription: "{count} kept out of your active schedule",
  trainingDays: "{count} training days", programWeeks: "{count}-week program", viewPlan: "View", editPlan: "Edit", moreActions: "More", setActive: "Set as active", duplicate: "Duplicate", archive: "Archive", deletePermanently: "Delete permanently", sourceManual: "Manual", sourceChatGpt: "ChatGPT", active: "Active", archived: "Archived",
  exerciseLibrary: "Exercise Library", exerciseLibraryDescription: "Browse exercises, guides, equipment, and movement details.", workoutHistory: "Workout History", workoutHistoryDescription: "Review completed and skipped sessions, sets, notes, and past performance.",
  chooseActivePlan: "Choose an active plan", noActivePlan: "Your plans are safe, but none controls Today", noActivePlanDescription: "Activate one plan to restore your weekly schedule.", activateNamed: "Activate {name}",
  planLoadFailed: "Workout plans could not load", planLoadFailedDescription: "Your workout plans could not load. Your saved data was not changed.", activityUnavailable: "Workout status is temporarily unavailable. No session was started or changed.", tryAgain: "Try again.",
  activePlanUpdated: "Active plan updated", activePlanUpdatedDescription: "{name} now controls your training schedule.", activateFailed: "Could not activate plan", activateFailedDescription: "Your active plan was not changed.", planDuplicated: "Plan duplicated", planDuplicatedDescription: "{name} copy is ready to edit.", duplicateFailed: "Could not duplicate plan", duplicateFailedDescription: "Nothing was copied.", planArchived: "Plan archived", planArchivedDescription: "Workout history and stable exercise identities were kept.", archiveFailed: "Could not archive plan", archiveFailedDescription: "The plan remains available.", planDeleted: "Plan deleted", planDeletedDescription: "{name} was permanently removed.", deleteFailed: "Plan could not be deleted", deleteFailedDescription: "Plans with workout history must be archived instead.",
  deleteTitle: "Delete this plan?", deleteDescription: "Permanent deletion is allowed only when the plan has no workout history. Future scheduled-only rows are removed safely. Archive keeps history and is usually safer.",
  planWeek: "Plan week", planWeekDescription: "Choose any calendar day to review. Training is offered only for today's scheduled workout.", planUnavailable: "Plan unavailable", planNotFound: "This workout plan could not be found.", backToTrain: "Back to Train", noWorkoutDay: "No workout day", noExercisesDay: "No exercises in this day", noExercisesDayDescription: "Edit the plan to add exercises.", reviewOnly: "Review only", statusUnavailable: "Status unavailable", adjustPlan: "Adjust plan", adjustPlanTitle: "Want to change the plan?", adjustPlanDescription: "Ask ChatGPT with only this plan and selected day as context.",
  planDetailsDescription: "Review this plan's complete seven-day structure and today's valid training action.", planNotChanged: "Plan was not changed",
  archivedMessage: "This plan no longer controls your schedule.", restoreActivate: "Restore or activate", planMetadata: "{days} training days · {exercises} exercises", unscheduled: "Unscheduled", general: "General", noEquipment: "No equipment", setsReps: "{sets} sets · {reps} reps", secondsRest: "{count}s rest",
  planDetails: "Plan details", editPlanTitle: "Edit Plan", saveChanges: "Save changes", cancel: "Cancel", back: "Back", noUnsavedChanges: "No unsaved changes", unsavedChanges: "Unsaved changes", saving: "Saving", saved: "Saved", saveFailed: "Save failed",
  builderTitle: "Create Plan", builderDescription: "Build a workout plan manually. Nothing is written until you save it.", planDetailsStep: "Plan details", trainingDaysStep: "Training days", reviewStep: "Review", continue: "Continue", savePlan: "Save plan", savingPlan: "Saving…",
  builderProgress: "Plan builder progress", programDuration: "Program duration", sessionDuration: "Session duration", noExercisesAdded: "No exercises", addExercisesToContinue: "Add at least one exercise to continue", selectedDay: "Selected", planName: "Plan name", goal: "Goal", goalPlaceholder: "Strength, endurance, mobility…", weeks: "Weeks", minutes: "Minutes", descriptionOptional: "Description (optional)", enterPlanName: "Enter a plan name.", trainingDaysHeading: "Training days", trainingDaysDescription: "Set each day, then choose and prescribe its exercises.", addDay: "Add day", dayName: "Day name", weekday: "Weekday", dayNotes: "Day notes", dayNotesPlaceholder: "Optional focus or coaching note", selectedCount: "{count} selected", selectedExercises: "Selected exercises", prescriptionHelp: "Edit sets, reps, rest and notes. Use the arrows to set the workout order.", noExercisesYet: "No exercises yet", chooseExercises: "Choose one or more exercises from the picker.", addExercises: "Add exercises", sets: "Sets", reps: "Reps", restSeconds: "Rest sec", notes: "Notes", moveUp: "Move {name} up", moveDown: "Move {name} down", removeItem: "Remove {name}", uniqueWeekdayError: "Give every training day a name and a unique weekday.", everyDayExerciseError: "Select at least one exercise for every training day.", atomicCreateNotice: "Saving writes every day and exercise together, then activates this plan. It does not start, complete, or skip a workout.",
  closePicker: "Close exercise picker", addExercisesTo: "Add exercises to {day}", selectionPreserved: "{count} selected. Selection is preserved while filters change.", searchExercises: "Search exercises", primaryMuscle: "Primary muscle", equipment: "Equipment", difficulty: "Difficulty", moreFilters: "More filters", muscleCategory: "Muscle category", secondaryMuscle: "Secondary muscle", forceType: "Force type", exerciseType: "Exercise type", mechanics: "Mechanics", viewGuide: "View guide", libraryLoadFailed: "The exercise library could not load.", alreadyAdded: "Already added", deselect: "Deselect", select: "Select", noExercisesFound: "No exercises found", broaderSearch: "Try a broader search or clear a filter.", clear: "Clear", addNExercises: "Add {count} exercises",
  editorDescription: "Update the whole plan, review every day, then apply everything with one save.", planNotFoundEditor: "This workout plan could not be found.", editorLoadFailed: "The editor could not load. Your saved plan was not changed.",
  addAtLeastOneDay: "Add at least one training day.", durationRange: "Plan duration must be between 1 and 104 weeks.", weekdayUnique: "Each scheduled weekday can only be used once.", dayNeedsName: "Every training day needs a name.", dayNeedsExercise: "{day} needs at least one exercise.", exerciseNeedsName: "Every exercise in {day} needs a name.", invalidPrescription: "{day} has invalid sets or rest values.",
  removeNamedDay: "Remove {name}?", removeDayDescription: "The day and its exercises leave this draft. Saved history identities are preserved when you save.", removeDay: "Remove day", removeNamedExercise: "Remove {name}?", removeExerciseDescription: "The exercise leaves this draft. Its saved history identity is preserved when you save.", removeExercise: "Remove exercise", thisExercise: "this exercise",
  planSaved: "Workout plan saved", planSavedDescription: "All plan changes were applied together.", couldNotSavePlan: "Could not save plan", draftPreserved: "Save failed. Your draft is still on this device.", discardChanges: "Discard plan changes?", discardChangesDescription: "This removes the local draft. The saved plan stays unchanged.", discardDraft: "Discard draft", editorUnavailable: "Editor unavailable", editorLoadFallback: "This plan could not load.",
  draftRestored: "Local draft restored", draftRestoredDescription: "These changes have not been saved to your plan yet.", durationWeeks: "Duration in weeks", description: "Description", selectDayToEdit: "Select a day to edit its schedule and exercises.", workoutDays: "Workout days", workoutDayNumber: "Workout day {count}", chooseThenEdit: "Choose exercises first, then edit prescriptions and workout order here.", exerciseNumber: "Exercise {count}", exerciseName: "Exercise name", target: "Target", targetPlaceholder: "Chest", atomicSaveNotice: "One save applies the complete plan atomically.",
  planCreated: "Workout plan created", planCreatedDescription: "{name} is now your active plan.", planCreateFailed: "Plan could not be created", planCreateDraftPreserved: "Nothing was saved. Your draft is still on this device.", unsavedTitle: "Unsaved plan changes", unsavedDescription: "Save the draft before leaving, discard it, or stay here.", applyContinue: "Save and continue", discardContinue: "Discard and continue", stay: "Stay here", workoutDayNotFound: "This workout day could not be found.", workoutDayOpenFailed: "This workout day could not be opened in the plan editor.", workoutDayUnavailable: "Workout day unavailable", openingPlanEditor: "Opening plan editor", pickerUnavailable: "Exercise picker unavailable", pickerOpenFailed: "The exercise picker could not be opened in the plan editor.", openingPicker: "Opening exercise picker",
  monday: "Monday", tuesday: "Tuesday", wednesday: "Wednesday", thursday: "Thursday", friday: "Friday", saturday: "Saturday", sunday: "Sunday"
} as const;

export type TrainKey = keyof typeof en;
type Dict = Record<TrainKey, string>;

const de: Dict = {
  myWorkout: "Mein Training", overviewDescription: "Sieh, was als Nächstes ansteht, verfolge deine Woche und verwalte deine Trainingspläne.", askChatGpt: "ChatGPT fragen", createPlan: "Plan erstellen", createWithChatGpt: "Mit ChatGPT erstellen", createManually: "Manuell erstellen",
  createFirstPlan: "Erstelle deinen ersten Trainingsplan", createFirstPlanDescription: "Nach dem Speichern erscheint dein Plan hier mit Bearbeitung, Durchführung, Verlauf und Korrekturen.", today: "Heute", todaysWorkout: "Heutiges Training", restDay: "Ruhetag", todayRestDay: "Heute ist ein Ruhetag", nextWorkout: "Nächstes Training: {workout} am {weekday}", viewWeeklyPlan: "Wochenplan ansehen",
  exercises: "{count} Übungen", aboutMinutes: "Etwa {count} Min.", checkingStatus: "Status wird geprüft…", retryStatus: "Status erneut laden", startWorkout: "Training starten", resumeWorkout: "Training fortsetzen", viewCompletedWorkout: "Abgeschlossenes Training ansehen", skippedToday: "Heute übersprungen", inProgress: "In Bearbeitung", completed: "Abgeschlossen", scheduled: "Geplant", rest: "Ruhe",
  thisWeek: "Diese Woche", thisWeekDescription: "Dein Zeitplan auf einen Blick. Starte oder setze nur über Heute oben fort.", todayLabel: "Heute", viewDay: "Tag ansehen", moreExercises: "+ {count} weitere", activePlan: "Aktiver Plan", activePlanDescription: "Dieser Plan steuert Heute und deinen Wochenplan.", otherPlans: "Andere Pläne", otherPlansDescription: "Alternativen bleiben kompakt, bis du sie brauchst.", archivedPlans: "Archivierte Pläne", archivedPlansDescription: "{count} außerhalb deines aktiven Zeitplans",
  trainingDays: "{count} Trainingstage", programWeeks: "{count}-Wochen-Programm", viewPlan: "Ansehen", editPlan: "Bearbeiten", moreActions: "Mehr", setActive: "Als aktiv festlegen", duplicate: "Duplizieren", archive: "Archivieren", deletePermanently: "Dauerhaft löschen", sourceManual: "Manuell", sourceChatGpt: "ChatGPT", active: "Aktiv", archived: "Archiviert",
  exerciseLibrary: "Übungsbibliothek", exerciseLibraryDescription: "Durchsuche Übungen, Anleitungen, Geräte und Bewegungsdetails.", workoutHistory: "Trainingsverlauf", workoutHistoryDescription: "Prüfe abgeschlossene und übersprungene Einheiten, Sätze, Notizen und frühere Leistungen.", chooseActivePlan: "Aktiven Plan auswählen", noActivePlan: "Deine Pläne sind sicher, aber keiner steuert Heute", noActivePlanDescription: "Aktiviere einen Plan, um deinen Wochenplan wiederherzustellen.", activateNamed: "{name} aktivieren",
  planLoadFailed: "Trainingspläne konnten nicht geladen werden", planLoadFailedDescription: "Deine Trainingspläne konnten nicht geladen werden. Gespeicherte Daten wurden nicht geändert.", activityUnavailable: "Der Trainingsstatus ist vorübergehend nicht verfügbar. Keine Einheit wurde gestartet oder geändert.", tryAgain: "Versuche es erneut.", activePlanUpdated: "Aktiver Plan aktualisiert", activePlanUpdatedDescription: "{name} steuert jetzt deinen Trainingsplan.", activateFailed: "Plan konnte nicht aktiviert werden", activateFailedDescription: "Dein aktiver Plan wurde nicht geändert.", planDuplicated: "Plan dupliziert", planDuplicatedDescription: "Die Kopie von {name} kann bearbeitet werden.", duplicateFailed: "Plan konnte nicht dupliziert werden", duplicateFailedDescription: "Nichts wurde kopiert.", planArchived: "Plan archiviert", planArchivedDescription: "Trainingsverlauf und stabile Übungsidentitäten wurden beibehalten.", archiveFailed: "Plan konnte nicht archiviert werden", archiveFailedDescription: "Der Plan bleibt verfügbar.", planDeleted: "Plan gelöscht", planDeletedDescription: "{name} wurde dauerhaft entfernt.", deleteFailed: "Plan konnte nicht gelöscht werden", deleteFailedDescription: "Pläne mit Trainingsverlauf müssen archiviert werden.", deleteTitle: "Diesen Plan löschen?", deleteDescription: "Dauerhaftes Löschen ist nur ohne Trainingsverlauf erlaubt. Nur zukünftige geplante Einträge werden sicher entfernt. Archivieren bewahrt den Verlauf.",
  planWeek: "Planwoche", planWeekDescription: "Wähle einen Kalendertag zur Ansicht. Training ist nur für das heutige geplante Training verfügbar.", planUnavailable: "Plan nicht verfügbar", planNotFound: "Dieser Trainingsplan wurde nicht gefunden.", backToTrain: "Zurück zu Training", noWorkoutDay: "Kein Trainingstag", noExercisesDay: "Keine Übungen an diesem Tag", noExercisesDayDescription: "Bearbeite den Plan, um Übungen hinzuzufügen.", reviewOnly: "Nur ansehen", statusUnavailable: "Status nicht verfügbar", adjustPlan: "Plan anpassen", adjustPlanTitle: "Möchtest du den Plan ändern?", adjustPlanDescription: "Frage ChatGPT nur mit diesem Plan und dem ausgewählten Tag als Kontext.", archivedMessage: "Dieser Plan steuert deinen Zeitplan nicht mehr.", restoreActivate: "Wiederherstellen oder aktivieren", planMetadata: "{days} Trainingstage · {exercises} Übungen", unscheduled: "Nicht geplant", general: "Allgemein", noEquipment: "Keine Geräte", setsReps: "{sets} Sätze · {reps} Wdh.", secondsRest: "{count}s Pause",
  planDetailsDescription: "Prüfe die vollständige Sieben-Tage-Struktur und die gültige Aktion für heute.", planNotChanged: "Plan wurde nicht geändert",
  planDetails: "Plandetails", editPlanTitle: "Plan bearbeiten", saveChanges: "Änderungen speichern", cancel: "Abbrechen", back: "Zurück", noUnsavedChanges: "Keine ungespeicherten Änderungen", unsavedChanges: "Ungespeicherte Änderungen", saving: "Wird gespeichert", saved: "Gespeichert", saveFailed: "Speichern fehlgeschlagen", builderTitle: "Plan erstellen", builderDescription: "Erstelle einen Trainingsplan manuell. Vor dem Speichern wird nichts geschrieben.", planDetailsStep: "Plandetails", trainingDaysStep: "Trainingstage", reviewStep: "Prüfen", continue: "Weiter", savePlan: "Plan speichern", savingPlan: "Wird gespeichert…",
  builderProgress: "Fortschritt des Plan-Builders", programDuration: "Programmdauer", sessionDuration: "Einheitsdauer", noExercisesAdded: "Keine Übungen", addExercisesToContinue: "Füge mindestens eine Übung hinzu, um fortzufahren", selectedDay: "Ausgewählt", planName: "Planname", goal: "Ziel", goalPlaceholder: "Kraft, Ausdauer, Mobilität…", weeks: "Wochen", minutes: "Minuten", descriptionOptional: "Beschreibung (optional)", enterPlanName: "Gib einen Plannamen ein.", trainingDaysHeading: "Trainingstage", trainingDaysDescription: "Lege jeden Tag fest, wähle Übungen und bearbeite ihre Vorgaben.", addDay: "Tag hinzufügen", dayName: "Tagesname", weekday: "Wochentag", dayNotes: "Tagesnotizen", dayNotesPlaceholder: "Optionaler Fokus oder Coaching-Hinweis", selectedCount: "{count} ausgewählt", selectedExercises: "Ausgewählte Übungen", prescriptionHelp: "Bearbeite Sätze, Wiederholungen, Pausen und Notizen. Lege die Reihenfolge mit den Pfeilen fest.", noExercisesYet: "Noch keine Übungen", chooseExercises: "Wähle eine oder mehrere Übungen aus.", addExercises: "Übungen hinzufügen", sets: "Sätze", reps: "Wiederholungen", restSeconds: "Pause in Sek.", notes: "Notizen", moveUp: "{name} nach oben", moveDown: "{name} nach unten", removeItem: "{name} entfernen", uniqueWeekdayError: "Gib jedem Trainingstag einen Namen und einen eindeutigen Wochentag.", everyDayExerciseError: "Wähle für jeden Trainingstag mindestens eine Übung.", atomicCreateNotice: "Beim Speichern werden alle Tage und Übungen zusammen geschrieben und der Plan aktiviert. Es wird kein Training gestartet, abgeschlossen oder übersprungen.",
  closePicker: "Übungsauswahl schließen", addExercisesTo: "Übungen zu {day} hinzufügen", selectionPreserved: "{count} ausgewählt. Die Auswahl bleibt beim Filtern erhalten.", searchExercises: "Übungen suchen", primaryMuscle: "Primärer Muskel", equipment: "Geräte", difficulty: "Schwierigkeit", moreFilters: "Weitere Filter", muscleCategory: "Muskelkategorie", secondaryMuscle: "Sekundärmuskel", forceType: "Kraftart", exerciseType: "Übungstyp", mechanics: "Mechanik", viewGuide: "Anleitung ansehen", libraryLoadFailed: "Die Übungsbibliothek konnte nicht geladen werden.", alreadyAdded: "Bereits hinzugefügt", deselect: "Abwählen", select: "Auswählen", noExercisesFound: "Keine Übungen gefunden", broaderSearch: "Erweitere die Suche oder lösche einen Filter.", clear: "Leeren", addNExercises: "{count} Übungen hinzufügen",
  editorDescription: "Aktualisiere den gesamten Plan, pr\u00fcfe jeden Tag und wende alles mit einem Speichervorgang an.", planNotFoundEditor: "Dieser Trainingsplan wurde nicht gefunden.", editorLoadFailed: "Der Editor konnte nicht geladen werden. Dein gespeicherter Plan wurde nicht ge\u00e4ndert.",
  addAtLeastOneDay: "F\u00fcge mindestens einen Trainingstag hinzu.", durationRange: "Die Plandauer muss zwischen 1 und 104 Wochen liegen.", weekdayUnique: "Jeder geplante Wochentag darf nur einmal verwendet werden.", dayNeedsName: "Jeder Trainingstag braucht einen Namen.", dayNeedsExercise: "{day} braucht mindestens eine \u00dcbung.", exerciseNeedsName: "Jede \u00dcbung in {day} braucht einen Namen.", invalidPrescription: "{day} enth\u00e4lt ung\u00fcltige Satz- oder Pausenwerte.",
  removeNamedDay: "{name} entfernen?", removeDayDescription: "Der Tag und seine \u00dcbungen werden aus diesem Entwurf entfernt. Gespeicherte Verlaufsidentit\u00e4ten bleiben beim Speichern erhalten.", removeDay: "Tag entfernen", removeNamedExercise: "{name} entfernen?", removeExerciseDescription: "Die \u00dcbung wird aus diesem Entwurf entfernt. Ihre gespeicherte Verlaufsidentit\u00e4t bleibt beim Speichern erhalten.", removeExercise: "\u00dcbung entfernen", thisExercise: "diese \u00dcbung",
  planSaved: "Trainingsplan gespeichert", planSavedDescription: "Alle Plan\u00e4nderungen wurden gemeinsam angewendet.", couldNotSavePlan: "Plan konnte nicht gespeichert werden", draftPreserved: "Speichern fehlgeschlagen. Dein Entwurf bleibt auf diesem Ger\u00e4t.", discardChanges: "Plan\u00e4nderungen verwerfen?", discardChangesDescription: "Der lokale Entwurf wird entfernt. Der gespeicherte Plan bleibt unver\u00e4ndert.", discardDraft: "Entwurf verwerfen", editorUnavailable: "Editor nicht verf\u00fcgbar", editorLoadFallback: "Dieser Plan konnte nicht geladen werden.",
  draftRestored: "Lokaler Entwurf wiederhergestellt", draftRestoredDescription: "Diese \u00c4nderungen wurden noch nicht im Plan gespeichert.", durationWeeks: "Dauer in Wochen", description: "Beschreibung", selectDayToEdit: "W\u00e4hle einen Tag, um Zeitplan und \u00dcbungen zu bearbeiten.", workoutDays: "Trainingstage", workoutDayNumber: "Trainingstag {count}", chooseThenEdit: "W\u00e4hle zuerst \u00dcbungen und bearbeite dann Vorgaben und Reihenfolge.", exerciseNumber: "\u00dcbung {count}", exerciseName: "\u00dcbungsname", target: "Zielmuskel", targetPlaceholder: "Brust", atomicSaveNotice: "Ein Speichervorgang wendet den gesamten Plan atomar an.",
  planCreated: "Trainingsplan erstellt", planCreatedDescription: "{name} ist jetzt dein aktiver Plan.", planCreateFailed: "Plan konnte nicht erstellt werden", planCreateDraftPreserved: "Nichts wurde gespeichert. Dein Entwurf bleibt auf diesem Ger\u00e4t.", unsavedTitle: "Ungespeicherte Plan\u00e4nderungen", unsavedDescription: "Speichere den Entwurf vor dem Verlassen, verwirf ihn oder bleibe hier.", applyContinue: "Speichern und fortfahren", discardContinue: "Verwerfen und fortfahren", stay: "Hier bleiben", workoutDayNotFound: "Dieser Trainingstag wurde nicht gefunden.", workoutDayOpenFailed: "Dieser Trainingstag konnte nicht im Planeditor ge\u00f6ffnet werden.", workoutDayUnavailable: "Trainingstag nicht verf\u00fcgbar", openingPlanEditor: "Planeditor wird ge\u00f6ffnet", pickerUnavailable: "\u00dcbungsauswahl nicht verf\u00fcgbar", pickerOpenFailed: "Die \u00dcbungsauswahl konnte nicht im Planeditor ge\u00f6ffnet werden.", openingPicker: "\u00dcbungsauswahl wird ge\u00f6ffnet",
  monday: "Montag", tuesday: "Dienstag", wednesday: "Mittwoch", thursday: "Donnerstag", friday: "Freitag", saturday: "Samstag", sunday: "Sonntag"
};

const ar: Dict = {
  myWorkout: "تماريني", overviewDescription: "اعرف ما هو قادم، وتابع أسبوعك، ونظّم خططك التدريبية.", askChatGpt: "اسأل ChatGPT", createPlan: "إنشاء خطة", createWithChatGpt: "إنشاء باستخدام ChatGPT", createManually: "إنشاء يدوي",
  createFirstPlan: "أنشئ أول خطة تدريبية", createFirstPlanDescription: "بعد الحفظ ستظهر خطتك هنا مع التعديل والتنفيذ والسجل والتصحيح.", today: "اليوم", todaysWorkout: "تمرين اليوم", restDay: "يوم راحة", todayRestDay: "اليوم هو يوم راحة", nextWorkout: "التمرين التالي: {workout} يوم {weekday}", viewWeeklyPlan: "عرض الخطة الأسبوعية",
  exercises: "{count} تمارين", aboutMinutes: "حوالي {count} دقيقة", checkingStatus: "جارٍ التحقق من الحالة…", retryStatus: "إعادة تحميل الحالة", startWorkout: "ابدأ التمرين", resumeWorkout: "استكمل التمرين", viewCompletedWorkout: "عرض التمرين المكتمل", skippedToday: "تم التخطي اليوم", inProgress: "قيد التنفيذ", completed: "مكتمل", scheduled: "مجدول", rest: "راحة",
  thisWeek: "هذا الأسبوع", thisWeekDescription: "جدولك في لمحة. ابدأ أو استكمل فقط من قسم اليوم أعلاه.", todayLabel: "اليوم", viewDay: "عرض اليوم", moreExercises: "+ {count} أخرى", activePlan: "الخطة النشطة", activePlanDescription: "هذه الخطة تتحكم في اليوم وجدولك الأسبوعي.", otherPlans: "خطط أخرى", otherPlansDescription: "تبقى البدائل مختصرة حتى تحتاجها.", archivedPlans: "الخطط المؤرشفة", archivedPlansDescription: "{count} خارج جدولك النشط",
  trainingDays: "{count} أيام تدريب", programWeeks: "برنامج لمدة {count} أسابيع", viewPlan: "عرض", editPlan: "تعديل", moreActions: "المزيد", setActive: "تعيين كنشطة", duplicate: "نسخ", archive: "أرشفة", deletePermanently: "حذف نهائي", sourceManual: "يدوي", sourceChatGpt: "ChatGPT", active: "نشطة", archived: "مؤرشفة",
  exerciseLibrary: "مكتبة التمارين", exerciseLibraryDescription: "تصفح التمارين والإرشادات والمعدات وتفاصيل الحركة.", workoutHistory: "سجل التمارين", workoutHistoryDescription: "راجع الجلسات المكتملة والمتخطاة والمجموعات والملاحظات والأداء السابق.", chooseActivePlan: "اختر خطة نشطة", noActivePlan: "خططك محفوظة، لكن لا توجد خطة تتحكم في اليوم", noActivePlanDescription: "فعّل خطة لاستعادة جدولك الأسبوعي.", activateNamed: "تفعيل {name}",
  planLoadFailed: "تعذر تحميل خطط التمرين", planLoadFailedDescription: "تعذر تحميل خططك التدريبية. لم تتغير بياناتك المحفوظة.", activityUnavailable: "حالة التمرين غير متاحة مؤقتًا. لم تبدأ أو تتغير أي جلسة.", tryAgain: "حاول مرة أخرى.", activePlanUpdated: "تم تحديث الخطة النشطة", activePlanUpdatedDescription: "تتحكم {name} الآن في جدولك التدريبي.", activateFailed: "تعذر تفعيل الخطة", activateFailedDescription: "لم تتغير خطتك النشطة.", planDuplicated: "تم نسخ الخطة", planDuplicatedDescription: "نسخة {name} جاهزة للتعديل.", duplicateFailed: "تعذر نسخ الخطة", duplicateFailedDescription: "لم يتم نسخ شيء.", planArchived: "تمت أرشفة الخطة", planArchivedDescription: "تم الاحتفاظ بسجل التمرين وهويات التمارين الثابتة.", archiveFailed: "تعذرت أرشفة الخطة", archiveFailedDescription: "تظل الخطة متاحة.", planDeleted: "تم حذف الخطة", planDeletedDescription: "تمت إزالة {name} نهائيًا.", deleteFailed: "تعذر حذف الخطة", deleteFailedDescription: "يجب أرشفة الخطط التي لها سجل تمرين.", deleteTitle: "حذف هذه الخطة؟", deleteDescription: "لا يُسمح بالحذف النهائي إلا إذا لم يوجد سجل تمرين. تزال المواعيد المستقبلية فقط بأمان. الأرشفة تحفظ السجل.",
  planWeek: "أسبوع الخطة", planWeekDescription: "اختر أي يوم لعرضه. يتاح التدريب فقط لتمرين اليوم المجدول.", planUnavailable: "الخطة غير متاحة", planNotFound: "تعذر العثور على خطة التمرين هذه.", backToTrain: "العودة إلى التدريب", noWorkoutDay: "لا يوجد يوم تمرين", noExercisesDay: "لا توجد تمارين في هذا اليوم", noExercisesDayDescription: "عدّل الخطة لإضافة تمارين.", reviewOnly: "عرض فقط", statusUnavailable: "الحالة غير متاحة", adjustPlan: "تعديل الخطة", adjustPlanTitle: "هل تريد تغيير الخطة؟", adjustPlanDescription: "اسأل ChatGPT باستخدام هذه الخطة واليوم المحدد فقط كسياق.", archivedMessage: "لم تعد هذه الخطة تتحكم في جدولك.", restoreActivate: "استعادة أو تفعيل", planMetadata: "{days} أيام تدريب · {exercises} تمارين", unscheduled: "غير مجدول", general: "عام", noEquipment: "بدون معدات", setsReps: "{sets} مجموعات · {reps} تكرارات", secondsRest: "راحة {count} ث",
  planDetailsDescription: "راجع بنية الخطة الكاملة لسبعة أيام وإجراء التدريب الصالح لليوم.", planNotChanged: "لم تتغير الخطة",
  planDetails: "تفاصيل الخطة", editPlanTitle: "تعديل الخطة", saveChanges: "حفظ التغييرات", cancel: "إلغاء", back: "رجوع", noUnsavedChanges: "لا توجد تغييرات غير محفوظة", unsavedChanges: "تغييرات غير محفوظة", saving: "جارٍ الحفظ", saved: "تم الحفظ", saveFailed: "فشل الحفظ", builderTitle: "إنشاء خطة", builderDescription: "أنشئ خطة تمرين يدويًا. لن يُكتب شيء قبل الحفظ.", planDetailsStep: "تفاصيل الخطة", trainingDaysStep: "أيام التدريب", reviewStep: "المراجعة", continue: "متابعة", savePlan: "حفظ الخطة", savingPlan: "جارٍ الحفظ…",
  builderProgress: "تقدم إنشاء الخطة", programDuration: "مدة البرنامج", sessionDuration: "مدة الجلسة", noExercisesAdded: "لا توجد تمارين", addExercisesToContinue: "أضف تمرينًا واحدًا على الأقل للمتابعة", selectedDay: "محدد", planName: "اسم الخطة", goal: "الهدف", goalPlaceholder: "القوة أو التحمل أو الحركة…", weeks: "الأسابيع", minutes: "الدقائق", descriptionOptional: "الوصف (اختياري)", enterPlanName: "أدخل اسم الخطة.", trainingDaysHeading: "أيام التدريب", trainingDaysDescription: "حدد كل يوم ثم اختر تمارينه وعدّل تفاصيلها.", addDay: "إضافة يوم", dayName: "اسم اليوم", weekday: "يوم الأسبوع", dayNotes: "ملاحظات اليوم", dayNotesPlaceholder: "تركيز أو ملاحظة تدريبية اختيارية", selectedCount: "تم تحديد {count}", selectedExercises: "التمارين المحددة", prescriptionHelp: "عدّل المجموعات والتكرارات والراحة والملاحظات، واستخدم الأسهم للترتيب.", noExercisesYet: "لا توجد تمارين بعد", chooseExercises: "اختر تمرينًا واحدًا أو أكثر.", addExercises: "إضافة تمارين", sets: "المجموعات", reps: "التكرارات", restSeconds: "الراحة بالثواني", notes: "الملاحظات", moveUp: "نقل {name} لأعلى", moveDown: "نقل {name} لأسفل", removeItem: "إزالة {name}", uniqueWeekdayError: "امنح كل يوم تدريب اسمًا ويوم أسبوع فريدًا.", everyDayExerciseError: "اختر تمرينًا واحدًا على الأقل لكل يوم تدريب.", atomicCreateNotice: "يحفظ الإجراء كل الأيام والتمارين معًا ثم يفعّل الخطة. لن يبدأ أو يكمل أو يتخطى تمرينًا.",
  closePicker: "إغلاق محدد التمارين", addExercisesTo: "إضافة تمارين إلى {day}", selectionPreserved: "تم تحديد {count}. يبقى التحديد محفوظًا عند تغيير عوامل التصفية.", searchExercises: "البحث عن تمارين", primaryMuscle: "العضلة الأساسية", equipment: "المعدات", difficulty: "الصعوبة", moreFilters: "المزيد من عوامل التصفية", muscleCategory: "فئة العضلات", secondaryMuscle: "العضلة الثانوية", forceType: "نوع القوة", exerciseType: "نوع التمرين", mechanics: "الميكانيكا", viewGuide: "عرض الدليل", libraryLoadFailed: "تعذر تحميل مكتبة التمارين.", alreadyAdded: "مضاف بالفعل", deselect: "إلغاء التحديد", select: "تحديد", noExercisesFound: "لم يتم العثور على تمارين", broaderSearch: "جرّب بحثًا أوسع أو امسح عامل تصفية.", clear: "مسح", addNExercises: "إضافة {count} تمارين",
  editorDescription: "حدّث الخطة كاملة، وراجع كل يوم، ثم طبّق كل شيء بعملية حفظ واحدة.", planNotFoundEditor: "تعذر العثور على خطة التمرين هذه.", editorLoadFailed: "تعذر تحميل المحرر. لم تتغير خطتك المحفوظة.",
  addAtLeastOneDay: "أضف يوم تدريب واحدًا على الأقل.", durationRange: "يجب أن تكون مدة الخطة بين أسبوع واحد و104 أسابيع.", weekdayUnique: "لا يمكن استخدام يوم الأسبوع المجدول إلا مرة واحدة.", dayNeedsName: "يحتاج كل يوم تدريب إلى اسم.", dayNeedsExercise: "يحتاج {day} إلى تمرين واحد على الأقل.", exerciseNeedsName: "يحتاج كل تمرين في {day} إلى اسم.", invalidPrescription: "يحتوي {day} على قيم غير صالحة للمجموعات أو الراحة.",
  removeNamedDay: "إزالة {name}؟", removeDayDescription: "سيغادر اليوم وتمارينه هذه المسودة. تبقى هويات السجل المحفوظة عند الحفظ.", removeDay: "إزالة اليوم", removeNamedExercise: "إزالة {name}؟", removeExerciseDescription: "سيغادر التمرين هذه المسودة. تبقى هوية سجله المحفوظة عند الحفظ.", removeExercise: "إزالة التمرين", thisExercise: "هذا التمرين",
  planSaved: "تم حفظ خطة التمرين", planSavedDescription: "تم تطبيق كل تغييرات الخطة معًا.", couldNotSavePlan: "تعذر حفظ الخطة", draftPreserved: "فشل الحفظ. مسودتك ما زالت على هذا الجهاز.", discardChanges: "تجاهل تغييرات الخطة؟", discardChangesDescription: "سيؤدي هذا إلى إزالة المسودة المحلية. تبقى الخطة المحفوظة دون تغيير.", discardDraft: "تجاهل المسودة", editorUnavailable: "المحرر غير متاح", editorLoadFallback: "تعذر تحميل هذه الخطة.",
  draftRestored: "تمت استعادة المسودة المحلية", draftRestoredDescription: "لم يتم حفظ هذه التغييرات في خطتك بعد.", durationWeeks: "المدة بالأسابيع", description: "الوصف", selectDayToEdit: "اختر يومًا لتعديل جدوله وتمارينه.", workoutDays: "أيام التمرين", workoutDayNumber: "يوم التمرين {count}", chooseThenEdit: "اختر التمارين أولًا، ثم عدّل الوصفات والترتيب هنا.", exerciseNumber: "التمرين {count}", exerciseName: "اسم التمرين", target: "العضلة المستهدفة", targetPlaceholder: "الصدر", atomicSaveNotice: "تطبّق عملية حفظ واحدة الخطة الكاملة بشكل ذري.",
  planCreated: "تم إنشاء خطة التمرين", planCreatedDescription: "أصبحت {name} الآن خطتك النشطة.", planCreateFailed: "تعذر إنشاء الخطة", planCreateDraftPreserved: "لم يتم حفظ شيء. مسودتك ما زالت على هذا الجهاز.", unsavedTitle: "تغييرات غير محفوظة في الخطة", unsavedDescription: "احفظ المسودة قبل المغادرة أو تجاهلها أو ابق هنا.", applyContinue: "الحفظ والمتابعة", discardContinue: "التجاهل والمتابعة", stay: "البقاء هنا", workoutDayNotFound: "تعذر العثور على يوم التمرين هذا.", workoutDayOpenFailed: "تعذر فتح يوم التمرين هذا في محرر الخطة.", workoutDayUnavailable: "يوم التمرين غير متاح", openingPlanEditor: "جارٍ فتح محرر الخطة", pickerUnavailable: "محدد التمارين غير متاح", pickerOpenFailed: "تعذر فتح محدد التمارين في محرر الخطة.", openingPicker: "جارٍ فتح محدد التمارين",
  monday: "الاثنين", tuesday: "الثلاثاء", wednesday: "الأربعاء", thursday: "الخميس", friday: "الجمعة", saturday: "السبت", sunday: "الأحد"
};

const dictionaries = { en, de, ar } as const;

function interpolate(template: string, values?: Record<string, string | number>) {
  if (!values) return template;
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), template);
}

export function translateTrain(language: SupportedLanguage, key: TrainKey, values?: Record<string, string | number>) {
  return interpolate(dictionaries[language][key] ?? en[key], values);
}

export function getTrainLocaleMetadata(language: SupportedLanguage) {
  return {
    dir: (language === "ar" ? "rtl" : "ltr") as "ltr" | "rtl",
    locale: language === "de" ? "de-DE" : language === "ar" ? "ar" : "en-US"
  };
}

export function useTrainTranslation() {
  const { language } = useTranslation();
  const { dir, locale } = getTrainLocaleMetadata(language);
  const tr = useCallback((key: TrainKey, values?: Record<string, string | number>) => translateTrain(language, key, values), [language]);
  return { language, dir, locale, tr };
}
