import type { SupportedLanguage } from "@/lib/i18n/types";

const en = {
  today: "Today",
  askChatGpt: "Ask ChatGPT",
  trainingDay: "Training day",
  restDay: "Rest day",
  todayProgress: "Today progress",
  calories: "Calories",
  protein: "Protein",
  carbs: "Carbs",
  fat: "Fat",
  water: "Water",
  loading: "Loading…",
  unavailable: "Unavailable",
  noTarget: "No target",
  targetUnavailable: "Target unavailable",
  targetValue: "{value} target",
  remainingValue: "{value} remaining",
  overTargetValue: "{value} over target",
  todayPlan: "Today's plan",
  todaysWorkout: "Today's workout",
  todaysMeals: "Today's meals",
  noWorkoutScheduled: "No workout scheduled today",
  openTrain: "Open Train",
  startWorkout: "Start workout",
  resumeWorkout: "Resume workout",
  viewWorkout: "View completed workout",
  exercisesCount: "{count} exercises",
  durationMinutes: "About {minutes} minutes",
  noMealsPlanned: "No meals planned today",
  openMealPlan: "Open meal plan",
  markDone: "Done",
  saving: "Saving…",
  skip: "Skip",
  skipAll: "Skip all",
  skipped: "Skipped",
  mealSaved: "Meal saved",
  mealSkipped: "Meal skipped",
  mealSkipFailed: "The meal was not skipped. Previous state was restored.",
  mealDoneFailed: "The meal was not logged. Retry when the connection is stable.",
  wellnessToday: "Wellness today",
  supplements: "Supplements",
  habits: "Habits",
  sleepRecovery: "Sleep & recovery",
  planned: "Planned",
  taken: "Taken",
  remaining: "Remaining",
  completed: "Completed",
  open: "Open",
  hoursSlept: "{hours} hours slept",
  sleepUnavailable: "No sleep data",
  recovery: "Recovery",
  fatigue: "Fatigue",
  lowRecovery: "Low recovery",
  noWellnessData: "No wellness information is saved for today.",
  openWellness: "Open Wellness",
  sectionUnavailable: "This information could not load.",
  someWellnessUnavailable: "Some wellness information is unavailable.",
  shoppingList: "Shopping list",
  bought: "bought",
  alreadyHave: "already have",
  boughtItems: "Bought items",
  openFullGrocery: "Open full grocery list",
  groceryUpdateFailed: "The grocery item was not updated. Previous state was restored.",
  breakfast: "Breakfast",
  lunch: "Lunch",
  dinner: "Dinner",
  snack: "Snack",
  retry: "Retry"
};

const de: typeof en = {
  today: "Heute",
  askChatGpt: "ChatGPT fragen",
  trainingDay: "Trainingstag",
  restDay: "Ruhetag",
  todayProgress: "Heutiger Fortschritt",
  calories: "Kalorien",
  protein: "Protein",
  carbs: "Kohlenhydrate",
  fat: "Fett",
  water: "Wasser",
  loading: "Wird geladen…",
  unavailable: "Nicht verfügbar",
  noTarget: "Kein Ziel",
  targetUnavailable: "Ziel nicht verfügbar",
  targetValue: "Ziel: {value}",
  remainingValue: "{value} verbleibend",
  overTargetValue: "{value} über dem Ziel",
  todayPlan: "Heutiger Plan",
  todaysWorkout: "Heutiges Training",
  todaysMeals: "Heutige Mahlzeiten",
  noWorkoutScheduled: "Heute ist kein Training geplant",
  openTrain: "Training öffnen",
  startWorkout: "Training starten",
  resumeWorkout: "Training fortsetzen",
  viewWorkout: "Abgeschlossenes Training öffnen",
  exercisesCount: "{count} Übungen",
  durationMinutes: "Etwa {minutes} Minuten",
  noMealsPlanned: "Heute sind keine Mahlzeiten geplant",
  openMealPlan: "Mahlzeitenplan öffnen",
  markDone: "Erledigt",
  saving: "Wird gespeichert…",
  skip: "Überspringen",
  skipAll: "Alle überspringen",
  skipped: "Übersprungen",
  mealSaved: "Mahlzeit gespeichert",
  mealSkipped: "Mahlzeit übersprungen",
  mealSkipFailed: "Die Mahlzeit wurde nicht übersprungen. Der vorherige Zustand wurde wiederhergestellt.",
  mealDoneFailed: "Die Mahlzeit wurde nicht protokolliert. Versuche es bei stabiler Verbindung erneut.",
  wellnessToday: "Wohlbefinden heute",
  supplements: "Supplemente",
  habits: "Gewohnheiten",
  sleepRecovery: "Schlaf & Erholung",
  planned: "Geplant",
  taken: "Eingenommen",
  remaining: "Verbleibend",
  completed: "Abgeschlossen",
  open: "Offen",
  hoursSlept: "{hours} Stunden Schlaf",
  sleepUnavailable: "Keine Schlafdaten",
  recovery: "Erholung",
  fatigue: "Müdigkeit",
  lowRecovery: "Niedrige Erholung",
  noWellnessData: "Für heute sind keine Wohlbefindensdaten gespeichert.",
  openWellness: "Wohlbefinden öffnen",
  sectionUnavailable: "Diese Informationen konnten nicht geladen werden.",
  someWellnessUnavailable: "Einige Wohlbefindensdaten sind nicht verfügbar.",
  shoppingList: "Einkaufsliste",
  bought: "gekauft",
  alreadyHave: "bereits vorhanden",
  boughtItems: "Gekaufte Artikel",
  openFullGrocery: "Vollständige Einkaufsliste öffnen",
  groceryUpdateFailed: "Der Artikel wurde nicht aktualisiert. Der vorherige Zustand wurde wiederhergestellt.",
  breakfast: "Frühstück",
  lunch: "Mittagessen",
  dinner: "Abendessen",
  snack: "Snack",
  retry: "Erneut versuchen"
};

const ar: typeof en = {
  today: "اليوم",
  askChatGpt: "اسأل ChatGPT",
  trainingDay: "يوم تدريب",
  restDay: "يوم راحة",
  todayProgress: "تقدم اليوم",
  calories: "السعرات",
  protein: "البروتين",
  carbs: "الكربوهيدرات",
  fat: "الدهون",
  water: "الماء",
  loading: "جارٍ التحميل…",
  unavailable: "غير متاح",
  noTarget: "لا يوجد هدف",
  targetUnavailable: "الهدف غير متاح",
  targetValue: "الهدف: {value}",
  remainingValue: "المتبقي: {value}",
  overTargetValue: "تجاوز الهدف بمقدار {value}",
  todayPlan: "خطة اليوم",
  todaysWorkout: "تمرين اليوم",
  todaysMeals: "وجبات اليوم",
  noWorkoutScheduled: "لا يوجد تمرين مجدول اليوم",
  openTrain: "فتح التدريب",
  startWorkout: "بدء التمرين",
  resumeWorkout: "متابعة التمرين",
  viewWorkout: "فتح التمرين المكتمل",
  exercisesCount: "{count} تمارين",
  durationMinutes: "حوالي {minutes} دقيقة",
  noMealsPlanned: "لا توجد وجبات مخططة اليوم",
  openMealPlan: "فتح خطة الوجبات",
  markDone: "تم",
  saving: "جارٍ الحفظ…",
  skip: "تخطّي",
  skipAll: "تخطّي الكل",
  skipped: "تم التخطّي",
  mealSaved: "تم حفظ الوجبة",
  mealSkipped: "تم تخطّي الوجبة",
  mealSkipFailed: "لم يتم تخطّي الوجبة وتمت استعادة الحالة السابقة.",
  mealDoneFailed: "لم يتم تسجيل الوجبة. أعد المحاولة عند استقرار الاتصال.",
  wellnessToday: "العافية اليوم",
  supplements: "المكملات",
  habits: "العادات",
  sleepRecovery: "النوم والتعافي",
  planned: "المخطط",
  taken: "تم تناوله",
  remaining: "المتبقي",
  completed: "المكتمل",
  open: "المفتوح",
  hoursSlept: "{hours} ساعات نوم",
  sleepUnavailable: "لا توجد بيانات نوم",
  recovery: "التعافي",
  fatigue: "الإرهاق",
  lowRecovery: "تعافٍ منخفض",
  noWellnessData: "لا توجد معلومات عافية محفوظة لليوم.",
  openWellness: "فتح العافية",
  sectionUnavailable: "تعذّر تحميل هذه المعلومات.",
  someWellnessUnavailable: "بعض معلومات العافية غير متاحة.",
  shoppingList: "قائمة المشتريات",
  bought: "تم شراؤه",
  alreadyHave: "موجود بالفعل",
  boughtItems: "العناصر المشتراة",
  openFullGrocery: "فتح قائمة المشتريات كاملة",
  groceryUpdateFailed: "لم يتم تحديث عنصر المشتريات وتمت استعادة الحالة السابقة.",
  breakfast: "الإفطار",
  lunch: "الغداء",
  dinner: "العشاء",
  snack: "وجبة خفيفة",
  retry: "إعادة المحاولة"
};

export type FocusedTodayCopy = typeof en;

export function getFocusedTodayCopy(language: SupportedLanguage): FocusedTodayCopy {
  return language === "de" ? de : language === "ar" ? ar : en;
}

export function interpolateFocusedTodayCopy(value: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce((result, [key, replacement]) => result.replaceAll(`{${key}}`, String(replacement)), value);
}
